#!/usr/bin/env bash
# Generates captain/CLI_REFERENCE.md from the spacetraders binary's --help tree.
# Regenerated at supervisor startup / make cli-reference so it can never drift
# from the installed binary (spec: Tool discovery §1).
set -euo pipefail

BIN="${1:-./bin/spacetraders}"
OUT="${2:-../captain/CLI_REFERENCE.md}"

if [ ! -x "$BIN" ]; then
  echo "error: $BIN not found or not executable (run: make build-cli)" >&2
  exit 1
fi

{
  echo "# spacetraders CLI reference"
  echo
  echo "> Generated by scripts/gen-cli-reference.sh — do not edit by hand."
  echo
  echo '```'
  "$BIN" --help 2>&1
  echo '```'

  # Walk one level of subcommands from the help output's Available Commands block.
  "$BIN" --help 2>&1 | awk '/Available Commands:/{f=1;next} /^Flags:/{f=0} f&&NF{print $1}' |
  while read -r cmd; do
    [ "$cmd" = "help" ] && continue
    echo
    echo "## spacetraders $cmd"
    echo '```'
    "$BIN" "$cmd" --help 2>&1
    echo '```'
    # Second level (e.g. container list, ledger report)
    "$BIN" "$cmd" --help 2>&1 | awk '/Available Commands:/{f=1;next} /^Flags:/{f=0} f&&NF{print $1}' |
    while read -r sub; do
      [ "$sub" = "help" ] && continue
      echo
      echo "### spacetraders $cmd $sub"
      echo '```'
      "$BIN" "$cmd" "$sub" --help 2>&1
      echo '```'
    done
  done
} > "$OUT"

echo "wrote $OUT"
