package main

import (
	"os"
	"path/filepath"
	"testing"
)

func mustAnalyze(t *testing.T, src string) *FileStat {
	t.Helper()
	st, err := AnalyzeFile("x.go", []byte(src))
	if err != nil {
		t.Fatalf("AnalyzeFile: %v", err)
	}
	if st == nil {
		t.Fatal("AnalyzeFile returned nil for a non-generated file")
	}
	return st
}

func TestAnalyzeFileCensusPartitionsEveryLine(t *testing.T) {
	src := `package p

// a doc comment
func F() {
	x := 1 // trailing
	_ = x
}
`
	st := mustAnalyze(t, src)
	if st.Comment+st.Blank+st.Code != st.Total {
		t.Fatalf("census does not partition: c=%d b=%d code=%d total=%d",
			st.Comment, st.Blank, st.Code, st.Total)
	}
	if st.Total != 7 {
		t.Fatalf("Total = %d, want 7", st.Total)
	}
	// "// a doc comment" and the trailing-comment line both count as comment.
	if st.Comment != 2 {
		t.Fatalf("Comment = %d, want 2", st.Comment)
	}
	if st.Blank != 1 {
		t.Fatalf("Blank = %d, want 1", st.Blank)
	}
}

func TestAnalyzeFileCountsBlockCommentSpan(t *testing.T) {
	src := `package p

/*
one
two
*/
func F() {}
`
	st := mustAnalyze(t, src)
	if st.Comment != 4 {
		t.Fatalf("Comment = %d, want 4 (whole block span)", st.Comment)
	}
}

// A regex census counts "//" inside a string as a comment. The parser does not,
// and that is why the tool parses.
func TestAnalyzeFileIgnoresSlashesInStringLiterals(t *testing.T) {
	src := `package p

func F() string {
	return "http://example.com // not a comment"
}
`
	st := mustAnalyze(t, src)
	if st.Comment != 0 {
		t.Fatalf("Comment = %d, want 0", st.Comment)
	}
}

func TestAnalyzeFileSkipsGeneratedFiles(t *testing.T) {
	src := `// Code generated by protoc-gen-go. DO NOT EDIT.

package p

// lots of comment
func F() {}
`
	st, err := AnalyzeFile("x.pb.go", []byte(src))
	if err != nil {
		t.Fatalf("AnalyzeFile: %v", err)
	}
	if st != nil {
		t.Fatalf("generated file was censused: %+v", st)
	}
}

func TestAnalyzeFileRejectsUnparseableSource(t *testing.T) {
	if _, err := AnalyzeFile("x.go", []byte("package p\nfunc {{{")); err == nil {
		t.Fatal("want a parse error, got nil")
	}
}

func TestAnalyzeFileRatio(t *testing.T) {
	src := `package p

// one
// two
func F() {}
`
	st := mustAnalyze(t, src)
	if got, want := st.Ratio(), 2.0/5.0; got != want {
		t.Fatalf("Ratio = %v, want %v", got, want)
	}
	if (FileStat{}).Ratio() != 0 {
		t.Fatal("empty FileStat must not divide by zero")
	}
}

func TestAnalyzeFileFlagsArchaeologyMarkers(t *testing.T) {
	src := `package p

// THE DEFECT IT CLOSES (sp-n2uve). Measured live: 2,257 waypoints.
// This previously used to hang; this fixed it. A bug was found.
func F() {}
`
	st := mustAnalyze(t, src)
	for _, name := range []string{
		"bead-id", "measured live", "the defect", "used to",
		"this fixed", "previously", "was found",
	} {
		if st.Markers[name] == 0 {
			t.Errorf("marker %q not flagged", name)
		}
	}
	if len(st.Hits) == 0 {
		t.Fatal("no marker hits recorded")
	}
	for _, h := range st.Hits {
		if h.Line < 3 || h.Line > 4 {
			t.Errorf("hit %+v: line outside the comment block", h)
		}
	}
}

// Markers are matched against comment text only. A bead id in a string constant
// is data, not archaeology.
func TestAnalyzeFileDoesNotFlagMarkersInCode(t *testing.T) {
	src := `package p

const BeadID = "sp-abcd"

func F() string { return "the defect" }
`
	st := mustAnalyze(t, src)
	if len(st.Markers) != 0 {
		t.Fatalf("markers flagged in code: %v", st.Markers)
	}
}

func TestScanAggregatesByPackageAndSkipsTests(t *testing.T) {
	root := t.TempDir()
	write := func(rel, body string) {
		t.Helper()
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("a/one.go", "package a\n\n// c\nfunc A() {}\n")
	write("a/two.go", "package a\n\n// c\n// c\nfunc B() {}\n")
	write("a/a_test.go", "package a\n\n// c\n// c\n// c\n// c\n// c\nfunc T() {}\n")
	write("b/one.go", "package b\n\nfunc C() {}\n")
	write("b/testdata/junk.go", "package junk\n\n// c\n// c\n// c\nfunc D() {}\n")
	write("b/vendor/v/v.go", "package v\n\n// c\n// c\n// c\nfunc E() {}\n")

	pkgs, err := Scan(root)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(pkgs) != 2 {
		t.Fatalf("packages = %d (%v), want 2 (a, b)", len(pkgs), keysOf(pkgs))
	}
	a := pkgs["a"]
	if a == nil {
		t.Fatal("package a missing")
	}
	if a.Files != 2 {
		t.Fatalf("a.Files = %d, want 2 (the _test.go file must be skipped)", a.Files)
	}
	if a.Comment != 3 {
		t.Fatalf("a.Comment = %d, want 3", a.Comment)
	}
	if b := pkgs["b"]; b == nil || b.Comment != 0 {
		t.Fatalf("package b = %+v, want a zero-comment package", b)
	}
}

func TestScanSkipsSiblingWorktrees(t *testing.T) {
	root := t.TempDir()
	mk := func(rel string) {
		t.Helper()
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("package p\n\n// c\nfunc F() {}\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	mk("real/f.go")
	mk(".claude/worktrees/other/x/f.go")

	pkgs, err := Scan(root)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(pkgs) != 1 || pkgs["real"] == nil {
		t.Fatalf("packages = %v, want only [real]", keysOf(pkgs))
	}
}

func TestSortedIsDescendingByRatioThenName(t *testing.T) {
	pkgs := map[string]*PkgStat{
		"low":  {Package: "low", Comment: 1, Total: 10},
		"high": {Package: "high", Comment: 9, Total: 10},
		"midB": {Package: "midB", Comment: 5, Total: 10},
		"midA": {Package: "midA", Comment: 5, Total: 10},
	}
	got := Sorted(pkgs)
	want := []string{"high", "midA", "midB", "low"}
	for i, w := range want {
		if got[i].Package != w {
			t.Fatalf("Sorted()[%d] = %s, want %s", i, got[i].Package, w)
		}
	}
}

func TestTotalSumsEveryPackage(t *testing.T) {
	pkgs := map[string]*PkgStat{
		"a": {Comment: 3, Total: 10, Code: 5, Blank: 2, Files: 1, Markers: map[string]int{"bead-id": 2}},
		"b": {Comment: 1, Total: 10, Code: 8, Blank: 1, Files: 2, Markers: map[string]int{"bead-id": 1, "used to": 1}},
	}
	tot := Total(pkgs)
	if tot.Comment != 4 || tot.Total != 20 || tot.Files != 3 {
		t.Fatalf("Total = %+v", tot)
	}
	if tot.MarkerTotal() != 4 {
		t.Fatalf("MarkerTotal = %d, want 4", tot.MarkerTotal())
	}
	if got, want := tot.Ratio(), 0.2; got != want {
		t.Fatalf("Ratio = %v, want %v", got, want)
	}
}

func keysOf(m map[string]*PkgStat) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
