package strip

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"path/filepath"
	"strings"
)

type Edit struct {
	Line   int    `json:"line"`
	Rule   string `json:"rule"`
	Before string `json:"before"`
	After  string `json:"after"`
}

// Explanation records why one occurrence was left alone, for auditing the
// deferred population.
type Explanation struct {
	Line   int    `json:"line"`
	ID     string `json:"id"`
	Reason string `json:"reason"`
	Text   string `json:"text"`
}

type FileResult struct {
	Path               string         `json:"path"`
	Rel                string         `json:"rel"`
	Occurrences        int            `json:"occurrences"`
	LiteralOccurrences int            `json:"literalOccurrences"`
	Stripped           int            `json:"stripped"`
	IDsRemoved         int            `json:"idsRemoved"`
	LinesChanged       int            `json:"linesChanged"`
	Skips              map[string]int `json:"skips"`
	Vetoes             map[string]int `json:"vetoes"`
	Edits              []Edit         `json:"edits"`
	Explanations       []Explanation  `json:"explanations,omitempty"`
	Changed            bool           `json:"changed"`
	Skipped            string         `json:"skipped,omitempty"`
	Rejected           string         `json:"rejected,omitempty"`
	New                []byte         `json:"-"`
}

func (r *FileResult) bump(m map[string]int, k string) { m[k]++ }

// ASTHash canonicalises a file with comments DISCARDED. Mode 0 retains every
// BasicLit value, so one hash simultaneously proves "no code changed" and "no
// string literal changed".
//
// The pre-image must be the bytes read before editing, never a re-read of the
// working file. gofmt -r is never used anywhere near this: it silently DROPS
// inline comments, which would make this hash pass on a mangled file.
func ASTHash(name string, src []byte) (string, error) {
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, name, src, 0)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	if err := (&printer.Config{Mode: printer.RawFormat, Tabwidth: 8}).Fprint(&b, fs, f); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", sha256.Sum256(b.Bytes())), nil
}

// ProcessFile rewrites one file's comments and verifies the result. It never
// writes: the caller decides. A verification failure leaves Rejected set and
// Changed false, so the file is left untouched.
func ProcessFile(root, abs string, src []byte, idx *LiteralIndex, opts Options) (*FileResult, error) {
	rel, _ := filepath.Rel(root, abs)
	res := &FileResult{
		Path:   abs,
		Rel:    filepath.ToSlash(rel),
		Skips:  map[string]int{},
		Vetoes: map[string]int{},
	}

	head := src
	if len(head) > 400 {
		head = head[:400]
	}
	if bytes.Contains(head, []byte("Code generated by")) {
		res.Skipped = "G0-GEN"
		return res, nil
	}
	if bytes.Contains(src, []byte("\r\n")) {
		res.Skipped = "G0-CRLF"
		return res, nil
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, abs, src, parser.ParseComments)
	if err != nil {
		res.Rejected = "parse: " + err.Error()
		return res, nil
	}

	docOf := docGroups(f)
	base := idx.For(root, abs, opts.LiteralScope)
	lines := strings.Split(string(src), "\n")

	for _, cg := range f.Comments {
		for i, c := range cg.List {
			n := len(IDPattern.FindAllString(c.Text, -1))
			res.Occurrences += n

			if kind := ClassifyComment(c.Text); kind != "" {
				res.Skips[kind] += n
				if opts.Explain {
					for _, id := range IDPattern.FindAllString(c.Text, -1) {
						res.Explanations = append(res.Explanations, Explanation{
							Line: fset.Position(c.Pos()).Line, ID: id, Reason: kind, Text: c.Text,
						})
					}
				}
				continue
			}

			pos := fset.Position(c.Pos())
			li, col := pos.Line-1, pos.Column-1
			if li < 0 || li >= len(lines) || col < 0 || col > len(lines[li]) {
				res.Rejected = fmt.Sprintf("comment position out of range at %d:%d", pos.Line, pos.Column)
				return res, nil
			}
			if lines[li][col:] != c.Text {
				res.Rejected = fmt.Sprintf("comment text does not match line %d", pos.Line)
				return res, nil
			}

			lits := base
			if opts.LiteralScope == ScopeDecl {
				lits = idx.ForDecl(abs, pos.Offset)
			}
			name, isDoc := docOf[cg]
			// The PREVIOUS comment node in the same group, unrewritten. Without
			// it a line-initial id cannot be told apart from the point where a
			// wrapped sentence happened to break.
			prev := ""
			if i > 0 {
				prev = cg.List[i-1].Text
			}
			ctx := LineCtx{IsDocFirstLine: isDoc && i == 0, DeclName: name, PrevLine: prev}

			lr := RewriteComment(c.Text, lits, opts, ctx)
			for _, s := range lr.Skips {
				res.bump(res.Skips, s.Reason)
				if opts.Explain {
					res.Explanations = append(res.Explanations, Explanation{
						Line: pos.Line, ID: s.ID, Reason: s.Reason, Text: lr.Text,
					})
				}
			}
			for _, v := range lr.Vetoes {
				res.bump(res.Vetoes, v.ID+"/"+v.Rule)
			}
			if lr.Text == c.Text {
				continue
			}
			res.Stripped += len(lr.Rules)
			res.IDsRemoved += n - len(IDPattern.FindAllString(lr.Text, -1))
			res.LinesChanged++
			for _, ru := range lr.Rules {
				res.Edits = append(res.Edits, Edit{Line: pos.Line, Rule: ru, Before: c.Text, After: lr.Text})
			}
			lines[li] = lines[li][:col] + lr.Text
		}
	}

	ast.Inspect(f, func(nd ast.Node) bool {
		if lit, ok := nd.(*ast.BasicLit); ok && lit.Kind == token.STRING {
			res.LiteralOccurrences += len(IDPattern.FindAllString(lit.Value, -1))
		}
		return true
	})

	if res.LinesChanged == 0 {
		return res, nil
	}
	out := []byte(strings.Join(lines, "\n"))
	if reason := verify(abs, src, out); reason != "" {
		res.Rejected = reason
		res.Changed = false
		res.New = nil
		return res, nil
	}
	res.Changed = true
	res.New = out
	return res, nil
}

// verify is the gate. Anything it flags leaves the file untouched.
func verify(abs string, before, after []byte) string {
	h1, err := ASTHash(abs, before)
	if err != nil {
		return "pre-image parse: " + err.Error()
	}
	h2, err := ASTHash(abs, after)
	if err != nil {
		return "post-image parse: " + err.Error()
	}
	if h1 != h2 {
		return "AST hash mismatch"
	}
	if bytes.Count(before, []byte("\n")) != bytes.Count(after, []byte("\n")) {
		return "line count changed"
	}
	nb, gb, err := commentCounts(abs, before)
	if err != nil {
		return "pre-image comment scan: " + err.Error()
	}
	na, ga, err := commentCounts(abs, after)
	if err != nil {
		return "post-image comment scan: " + err.Error()
	}
	if nb != na {
		return fmt.Sprintf("comment nodes %d -> %d", nb, na)
	}
	if gb != ga {
		return fmt.Sprintf("comment groups %d -> %d", gb, ga)
	}
	if !equalBags(literalIDs(abs, before), literalIDs(abs, after)) {
		return "string-literal bead ids changed"
	}
	if lost := missingWords(proseWords(before), proseWords(after)); len(lost) > 0 {
		return "prose words lost: " + strings.Join(lost, ",")
	}
	bl := strings.Split(string(before), "\n")
	al := strings.Split(string(after), "\n")
	for i := range bl {
		if bl[i] == al[i] {
			continue
		}
		switch {
		case leadWS(bl[i]) != leadWS(al[i]):
			return fmt.Sprintf("line %d: leading indent changed", i+1)
		case !sameRunOffsets(bl[i], al[i]):
			return fmt.Sprintf("line %d: column runs shifted", i+1)
		case strings.TrimRight(al[i], " \t") != al[i]:
			return fmt.Sprintf("line %d: trailing whitespace introduced", i+1)
		}
		for _, d := range DefectChecks {
			if d.Re.MatchString(al[i]) && !d.Re.MatchString(bl[i]) {
				return fmt.Sprintf("line %d: introduced defect %s", i+1, d.ID)
			}
		}
	}
	return ""
}

func commentCounts(name string, src []byte) (nodes, groups int, err error) {
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, name, src, parser.ParseComments)
	if err != nil {
		return 0, 0, err
	}
	for _, cg := range f.Comments {
		groups++
		nodes += len(cg.List)
	}
	return nodes, groups, nil
}

func literalIDs(name string, src []byte) map[string]int {
	out := map[string]int{}
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, name, src, 0)
	if err != nil {
		return out
	}
	ast.Inspect(f, func(n ast.Node) bool {
		if lit, ok := n.(*ast.BasicLit); ok && lit.Kind == token.STRING {
			for _, id := range IDPattern.FindAllString(lit.Value, -1) {
				out[id]++
			}
		}
		return true
	})
	return out
}

func equalBags(a, b map[string]int) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if b[k] != v {
			return false
		}
	}
	return true
}

// docGroups maps every declaration Doc group to the identifier it documents,
// so V12 can refuse to regress a godoc first line.
func docGroups(f *ast.File) map[*ast.CommentGroup]string {
	out := map[*ast.CommentGroup]string{}
	put := func(cg *ast.CommentGroup, name string) {
		if cg != nil {
			out[cg] = name
		}
	}
	ast.Inspect(f, func(n ast.Node) bool {
		switch d := n.(type) {
		case *ast.FuncDecl:
			put(d.Doc, d.Name.Name)
		case *ast.GenDecl:
			put(d.Doc, genDeclName(d))
		case *ast.TypeSpec:
			put(d.Doc, d.Name.Name)
		case *ast.ValueSpec:
			if len(d.Names) > 0 {
				put(d.Doc, d.Names[0].Name)
			}
		case *ast.Field:
			if len(d.Names) > 0 {
				put(d.Doc, d.Names[0].Name)
			}
		}
		return true
	})
	return out
}

func genDeclName(d *ast.GenDecl) string {
	if len(d.Specs) == 0 {
		return ""
	}
	switch s := d.Specs[0].(type) {
	case *ast.TypeSpec:
		return s.Name.Name
	case *ast.ValueSpec:
		if len(s.Names) > 0 {
			return s.Names[0].Name
		}
	}
	return ""
}
