// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pkg/proto/daemon/daemon.proto

package daemon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_NavigateShip_FullMethodName             = "/daemon.DaemonService/NavigateShip"
	DaemonService_DockShip_FullMethodName                 = "/daemon.DaemonService/DockShip"
	DaemonService_OrbitShip_FullMethodName                = "/daemon.DaemonService/OrbitShip"
	DaemonService_RefuelShip_FullMethodName               = "/daemon.DaemonService/RefuelShip"
	DaemonService_BatchContractWorkflow_FullMethodName    = "/daemon.DaemonService/BatchContractWorkflow"
	DaemonService_ContractFleetCoordinator_FullMethodName = "/daemon.DaemonService/ContractFleetCoordinator"
	DaemonService_ScoutTour_FullMethodName                = "/daemon.DaemonService/ScoutTour"
	DaemonService_ScoutMarkets_FullMethodName             = "/daemon.DaemonService/ScoutMarkets"
	DaemonService_AssignScoutingFleet_FullMethodName      = "/daemon.DaemonService/AssignScoutingFleet"
	DaemonService_ListContainers_FullMethodName           = "/daemon.DaemonService/ListContainers"
	DaemonService_GetContainer_FullMethodName             = "/daemon.DaemonService/GetContainer"
	DaemonService_StopContainer_FullMethodName            = "/daemon.DaemonService/StopContainer"
	DaemonService_GetContainerLogs_FullMethodName         = "/daemon.DaemonService/GetContainerLogs"
	DaemonService_HealthCheck_FullMethodName              = "/daemon.DaemonService/HealthCheck"
	DaemonService_ListShips_FullMethodName                = "/daemon.DaemonService/ListShips"
	DaemonService_GetShip_FullMethodName                  = "/daemon.DaemonService/GetShip"
	DaemonService_PurchaseShip_FullMethodName             = "/daemon.DaemonService/PurchaseShip"
	DaemonService_BatchPurchaseShips_FullMethodName       = "/daemon.DaemonService/BatchPurchaseShips"
	DaemonService_GetShipyardListings_FullMethodName      = "/daemon.DaemonService/GetShipyardListings"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService defines the gRPC API for CLI <-> Daemon communication
// Communication occurs over Unix domain socket for security and performance
type DaemonServiceClient interface {
	// NavigateShip initiates a ship navigation operation as a background container
	NavigateShip(ctx context.Context, in *NavigateShipRequest, opts ...grpc.CallOption) (*NavigateShipResponse, error)
	// DockShip docks a ship at its current location
	DockShip(ctx context.Context, in *DockShipRequest, opts ...grpc.CallOption) (*DockShipResponse, error)
	// OrbitShip puts a ship into orbit from docked position
	OrbitShip(ctx context.Context, in *OrbitShipRequest, opts ...grpc.CallOption) (*OrbitShipResponse, error)
	// RefuelShip refuels a ship at its current location
	RefuelShip(ctx context.Context, in *RefuelShipRequest, opts ...grpc.CallOption) (*RefuelShipResponse, error)
	// BatchContractWorkflow executes batch contract workflow operations
	BatchContractWorkflow(ctx context.Context, in *BatchContractWorkflowRequest, opts ...grpc.CallOption) (*BatchContractWorkflowResponse, error)
	// ContractFleetCoordinator manages a pool of ships for continuous contract execution
	ContractFleetCoordinator(ctx context.Context, in *ContractFleetCoordinatorRequest, opts ...grpc.CallOption) (*ContractFleetCoordinatorResponse, error)
	// ScoutTour executes market scouting tour operations (single ship)
	ScoutTour(ctx context.Context, in *ScoutTourRequest, opts ...grpc.CallOption) (*ScoutTourResponse, error)
	// ScoutMarkets orchestrates fleet deployment for market scouting (multi-ship with VRP)
	ScoutMarkets(ctx context.Context, in *ScoutMarketsRequest, opts ...grpc.CallOption) (*ScoutMarketsResponse, error)
	// AssignScoutingFleet auto-discovers probe/satellite ships and assigns them to scout markets
	AssignScoutingFleet(ctx context.Context, in *AssignScoutingFleetRequest, opts ...grpc.CallOption) (*AssignScoutingFleetResponse, error)
	// ListContainers returns all running background containers
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	// GetContainer returns detailed information about a specific container
	GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error)
	// StopContainer stops a running background container
	StopContainer(ctx context.Context, in *StopContainerRequest, opts ...grpc.CallOption) (*StopContainerResponse, error)
	// GetContainerLogs retrieves logs from a container
	GetContainerLogs(ctx context.Context, in *GetContainerLogsRequest, opts ...grpc.CallOption) (*GetContainerLogsResponse, error)
	// HealthCheck verifies daemon is running and responsive
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// ListShips returns all ships for a player
	ListShips(ctx context.Context, in *ListShipsRequest, opts ...grpc.CallOption) (*ListShipsResponse, error)
	// GetShip returns detailed information about a specific ship
	GetShip(ctx context.Context, in *GetShipRequest, opts ...grpc.CallOption) (*GetShipResponse, error)
	// PurchaseShip purchases a single ship from a shipyard
	PurchaseShip(ctx context.Context, in *PurchaseShipRequest, opts ...grpc.CallOption) (*PurchaseShipResponse, error)
	// BatchPurchaseShips purchases multiple ships from a shipyard as a background operation
	BatchPurchaseShips(ctx context.Context, in *BatchPurchaseShipsRequest, opts ...grpc.CallOption) (*BatchPurchaseShipsResponse, error)
	// GetShipyardListings retrieves available ships at a shipyard
	GetShipyardListings(ctx context.Context, in *GetShipyardListingsRequest, opts ...grpc.CallOption) (*GetShipyardListingsResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) NavigateShip(ctx context.Context, in *NavigateShipRequest, opts ...grpc.CallOption) (*NavigateShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_NavigateShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DockShip(ctx context.Context, in *DockShipRequest, opts ...grpc.CallOption) (*DockShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_DockShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) OrbitShip(ctx context.Context, in *OrbitShipRequest, opts ...grpc.CallOption) (*OrbitShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrbitShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_OrbitShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RefuelShip(ctx context.Context, in *RefuelShipRequest, opts ...grpc.CallOption) (*RefuelShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefuelShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_RefuelShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) BatchContractWorkflow(ctx context.Context, in *BatchContractWorkflowRequest, opts ...grpc.CallOption) (*BatchContractWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchContractWorkflowResponse)
	err := c.cc.Invoke(ctx, DaemonService_BatchContractWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ContractFleetCoordinator(ctx context.Context, in *ContractFleetCoordinatorRequest, opts ...grpc.CallOption) (*ContractFleetCoordinatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractFleetCoordinatorResponse)
	err := c.cc.Invoke(ctx, DaemonService_ContractFleetCoordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ScoutTour(ctx context.Context, in *ScoutTourRequest, opts ...grpc.CallOption) (*ScoutTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoutTourResponse)
	err := c.cc.Invoke(ctx, DaemonService_ScoutTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ScoutMarkets(ctx context.Context, in *ScoutMarketsRequest, opts ...grpc.CallOption) (*ScoutMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoutMarketsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ScoutMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) AssignScoutingFleet(ctx context.Context, in *AssignScoutingFleetRequest, opts ...grpc.CallOption) (*AssignScoutingFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignScoutingFleetResponse)
	err := c.cc.Invoke(ctx, DaemonService_AssignScoutingFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContainersResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopContainer(ctx context.Context, in *StopContainerRequest, opts ...grpc.CallOption) (*StopContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopContainerResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetContainerLogs(ctx context.Context, in *GetContainerLogsRequest, opts ...grpc.CallOption) (*GetContainerLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerLogsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetContainerLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DaemonService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListShips(ctx context.Context, in *ListShipsRequest, opts ...grpc.CallOption) (*ListShipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShipsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListShips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetShip(ctx context.Context, in *GetShipRequest, opts ...grpc.CallOption) (*GetShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) PurchaseShip(ctx context.Context, in *PurchaseShipRequest, opts ...grpc.CallOption) (*PurchaseShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_PurchaseShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) BatchPurchaseShips(ctx context.Context, in *BatchPurchaseShipsRequest, opts ...grpc.CallOption) (*BatchPurchaseShipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPurchaseShipsResponse)
	err := c.cc.Invoke(ctx, DaemonService_BatchPurchaseShips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetShipyardListings(ctx context.Context, in *GetShipyardListingsRequest, opts ...grpc.CallOption) (*GetShipyardListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShipyardListingsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetShipyardListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService defines the gRPC API for CLI <-> Daemon communication
// Communication occurs over Unix domain socket for security and performance
type DaemonServiceServer interface {
	// NavigateShip initiates a ship navigation operation as a background container
	NavigateShip(context.Context, *NavigateShipRequest) (*NavigateShipResponse, error)
	// DockShip docks a ship at its current location
	DockShip(context.Context, *DockShipRequest) (*DockShipResponse, error)
	// OrbitShip puts a ship into orbit from docked position
	OrbitShip(context.Context, *OrbitShipRequest) (*OrbitShipResponse, error)
	// RefuelShip refuels a ship at its current location
	RefuelShip(context.Context, *RefuelShipRequest) (*RefuelShipResponse, error)
	// BatchContractWorkflow executes batch contract workflow operations
	BatchContractWorkflow(context.Context, *BatchContractWorkflowRequest) (*BatchContractWorkflowResponse, error)
	// ContractFleetCoordinator manages a pool of ships for continuous contract execution
	ContractFleetCoordinator(context.Context, *ContractFleetCoordinatorRequest) (*ContractFleetCoordinatorResponse, error)
	// ScoutTour executes market scouting tour operations (single ship)
	ScoutTour(context.Context, *ScoutTourRequest) (*ScoutTourResponse, error)
	// ScoutMarkets orchestrates fleet deployment for market scouting (multi-ship with VRP)
	ScoutMarkets(context.Context, *ScoutMarketsRequest) (*ScoutMarketsResponse, error)
	// AssignScoutingFleet auto-discovers probe/satellite ships and assigns them to scout markets
	AssignScoutingFleet(context.Context, *AssignScoutingFleetRequest) (*AssignScoutingFleetResponse, error)
	// ListContainers returns all running background containers
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	// GetContainer returns detailed information about a specific container
	GetContainer(context.Context, *GetContainerRequest) (*GetContainerResponse, error)
	// StopContainer stops a running background container
	StopContainer(context.Context, *StopContainerRequest) (*StopContainerResponse, error)
	// GetContainerLogs retrieves logs from a container
	GetContainerLogs(context.Context, *GetContainerLogsRequest) (*GetContainerLogsResponse, error)
	// HealthCheck verifies daemon is running and responsive
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// ListShips returns all ships for a player
	ListShips(context.Context, *ListShipsRequest) (*ListShipsResponse, error)
	// GetShip returns detailed information about a specific ship
	GetShip(context.Context, *GetShipRequest) (*GetShipResponse, error)
	// PurchaseShip purchases a single ship from a shipyard
	PurchaseShip(context.Context, *PurchaseShipRequest) (*PurchaseShipResponse, error)
	// BatchPurchaseShips purchases multiple ships from a shipyard as a background operation
	BatchPurchaseShips(context.Context, *BatchPurchaseShipsRequest) (*BatchPurchaseShipsResponse, error)
	// GetShipyardListings retrieves available ships at a shipyard
	GetShipyardListings(context.Context, *GetShipyardListingsRequest) (*GetShipyardListingsResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) NavigateShip(context.Context, *NavigateShipRequest) (*NavigateShipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NavigateShip not implemented")
}
func (UnimplementedDaemonServiceServer) DockShip(context.Context, *DockShipRequest) (*DockShipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockShip not implemented")
}
func (UnimplementedDaemonServiceServer) OrbitShip(context.Context, *OrbitShipRequest) (*OrbitShipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrbitShip not implemented")
}
func (UnimplementedDaemonServiceServer) RefuelShip(context.Context, *RefuelShipRequest) (*RefuelShipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefuelShip not implemented")
}
func (UnimplementedDaemonServiceServer) BatchContractWorkflow(context.Context, *BatchContractWorkflowRequest) (*BatchContractWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchContractWorkflow not implemented")
}
func (UnimplementedDaemonServiceServer) ContractFleetCoordinator(context.Context, *ContractFleetCoordinatorRequest) (*ContractFleetCoordinatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractFleetCoordinator not implemented")
}
func (UnimplementedDaemonServiceServer) ScoutTour(context.Context, *ScoutTourRequest) (*ScoutTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoutTour not implemented")
}
func (UnimplementedDaemonServiceServer) ScoutMarkets(context.Context, *ScoutMarketsRequest) (*ScoutMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoutMarkets not implemented")
}
func (UnimplementedDaemonServiceServer) AssignScoutingFleet(context.Context, *AssignScoutingFleetRequest) (*AssignScoutingFleetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignScoutingFleet not implemented")
}
func (UnimplementedDaemonServiceServer) ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedDaemonServiceServer) GetContainer(context.Context, *GetContainerRequest) (*GetContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainer not implemented")
}
func (UnimplementedDaemonServiceServer) StopContainer(context.Context, *StopContainerRequest) (*StopContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopContainer not implemented")
}
func (UnimplementedDaemonServiceServer) GetContainerLogs(context.Context, *GetContainerLogsRequest) (*GetContainerLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainerLogs not implemented")
}
func (UnimplementedDaemonServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDaemonServiceServer) ListShips(context.Context, *ListShipsRequest) (*ListShipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShips not implemented")
}
func (UnimplementedDaemonServiceServer) GetShip(context.Context, *GetShipRequest) (*GetShipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShip not implemented")
}
func (UnimplementedDaemonServiceServer) PurchaseShip(context.Context, *PurchaseShipRequest) (*PurchaseShipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseShip not implemented")
}
func (UnimplementedDaemonServiceServer) BatchPurchaseShips(context.Context, *BatchPurchaseShipsRequest) (*BatchPurchaseShipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPurchaseShips not implemented")
}
func (UnimplementedDaemonServiceServer) GetShipyardListings(context.Context, *GetShipyardListingsRequest) (*GetShipyardListingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShipyardListings not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_NavigateShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).NavigateShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_NavigateShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).NavigateShip(ctx, req.(*NavigateShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DockShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DockShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DockShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DockShip(ctx, req.(*DockShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_OrbitShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrbitShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).OrbitShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_OrbitShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).OrbitShip(ctx, req.(*OrbitShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RefuelShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefuelShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RefuelShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RefuelShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RefuelShip(ctx, req.(*RefuelShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_BatchContractWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchContractWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).BatchContractWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_BatchContractWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).BatchContractWorkflow(ctx, req.(*BatchContractWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ContractFleetCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractFleetCoordinatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ContractFleetCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ContractFleetCoordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ContractFleetCoordinator(ctx, req.(*ContractFleetCoordinatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ScoutTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoutTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ScoutTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ScoutTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ScoutTour(ctx, req.(*ScoutTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ScoutMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoutMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ScoutMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ScoutMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ScoutMarkets(ctx, req.(*ScoutMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_AssignScoutingFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignScoutingFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).AssignScoutingFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_AssignScoutingFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).AssignScoutingFleet(ctx, req.(*AssignScoutingFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetContainer(ctx, req.(*GetContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopContainer(ctx, req.(*StopContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetContainerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetContainerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetContainerLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetContainerLogs(ctx, req.(*GetContainerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListShips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListShips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListShips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListShips(ctx, req.(*ListShipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetShip(ctx, req.(*GetShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_PurchaseShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).PurchaseShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_PurchaseShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).PurchaseShip(ctx, req.(*PurchaseShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_BatchPurchaseShips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPurchaseShipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).BatchPurchaseShips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_BatchPurchaseShips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).BatchPurchaseShips(ctx, req.(*BatchPurchaseShipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetShipyardListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipyardListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetShipyardListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetShipyardListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetShipyardListings(ctx, req.(*GetShipyardListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NavigateShip",
			Handler:    _DaemonService_NavigateShip_Handler,
		},
		{
			MethodName: "DockShip",
			Handler:    _DaemonService_DockShip_Handler,
		},
		{
			MethodName: "OrbitShip",
			Handler:    _DaemonService_OrbitShip_Handler,
		},
		{
			MethodName: "RefuelShip",
			Handler:    _DaemonService_RefuelShip_Handler,
		},
		{
			MethodName: "BatchContractWorkflow",
			Handler:    _DaemonService_BatchContractWorkflow_Handler,
		},
		{
			MethodName: "ContractFleetCoordinator",
			Handler:    _DaemonService_ContractFleetCoordinator_Handler,
		},
		{
			MethodName: "ScoutTour",
			Handler:    _DaemonService_ScoutTour_Handler,
		},
		{
			MethodName: "ScoutMarkets",
			Handler:    _DaemonService_ScoutMarkets_Handler,
		},
		{
			MethodName: "AssignScoutingFleet",
			Handler:    _DaemonService_AssignScoutingFleet_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _DaemonService_ListContainers_Handler,
		},
		{
			MethodName: "GetContainer",
			Handler:    _DaemonService_GetContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _DaemonService_StopContainer_Handler,
		},
		{
			MethodName: "GetContainerLogs",
			Handler:    _DaemonService_GetContainerLogs_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DaemonService_HealthCheck_Handler,
		},
		{
			MethodName: "ListShips",
			Handler:    _DaemonService_ListShips_Handler,
		},
		{
			MethodName: "GetShip",
			Handler:    _DaemonService_GetShip_Handler,
		},
		{
			MethodName: "PurchaseShip",
			Handler:    _DaemonService_PurchaseShip_Handler,
		},
		{
			MethodName: "BatchPurchaseShips",
			Handler:    _DaemonService_BatchPurchaseShips_Handler,
		},
		{
			MethodName: "GetShipyardListings",
			Handler:    _DaemonService_GetShipyardListings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/daemon/daemon.proto",
}
