// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: pkg/proto/daemon/daemon.proto

package daemon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_NavigateShip_FullMethodName                          = "/daemon.DaemonService/NavigateShip"
	DaemonService_DockShip_FullMethodName                              = "/daemon.DaemonService/DockShip"
	DaemonService_OrbitShip_FullMethodName                             = "/daemon.DaemonService/OrbitShip"
	DaemonService_RefuelShip_FullMethodName                            = "/daemon.DaemonService/RefuelShip"
	DaemonService_JumpShip_FullMethodName                              = "/daemon.DaemonService/JumpShip"
	DaemonService_BatchContractWorkflow_FullMethodName                 = "/daemon.DaemonService/BatchContractWorkflow"
	DaemonService_ContractFleetCoordinator_FullMethodName              = "/daemon.DaemonService/ContractFleetCoordinator"
	DaemonService_ScoutTour_FullMethodName                             = "/daemon.DaemonService/ScoutTour"
	DaemonService_ScoutMarkets_FullMethodName                          = "/daemon.DaemonService/ScoutMarkets"
	DaemonService_AssignScoutingFleet_FullMethodName                   = "/daemon.DaemonService/AssignScoutingFleet"
	DaemonService_ListContainers_FullMethodName                        = "/daemon.DaemonService/ListContainers"
	DaemonService_GetContainer_FullMethodName                          = "/daemon.DaemonService/GetContainer"
	DaemonService_StopContainer_FullMethodName                         = "/daemon.DaemonService/StopContainer"
	DaemonService_GetContainerLogs_FullMethodName                      = "/daemon.DaemonService/GetContainerLogs"
	DaemonService_HealthCheck_FullMethodName                           = "/daemon.DaemonService/HealthCheck"
	DaemonService_GetAPIBudget_FullMethodName                          = "/daemon.DaemonService/GetAPIBudget"
	DaemonService_ListShips_FullMethodName                             = "/daemon.DaemonService/ListShips"
	DaemonService_GetShip_FullMethodName                               = "/daemon.DaemonService/GetShip"
	DaemonService_RefreshShip_FullMethodName                           = "/daemon.DaemonService/RefreshShip"
	DaemonService_ReserveShip_FullMethodName                           = "/daemon.DaemonService/ReserveShip"
	DaemonService_ReleaseShip_FullMethodName                           = "/daemon.DaemonService/ReleaseShip"
	DaemonService_AssignShipFleet_FullMethodName                       = "/daemon.DaemonService/AssignShipFleet"
	DaemonService_UnassignShipFleet_FullMethodName                     = "/daemon.DaemonService/UnassignShipFleet"
	DaemonService_ListFleets_FullMethodName                            = "/daemon.DaemonService/ListFleets"
	DaemonService_ListWaypoints_FullMethodName                         = "/daemon.DaemonService/ListWaypoints"
	DaemonService_GetWaypoint_FullMethodName                           = "/daemon.DaemonService/GetWaypoint"
	DaemonService_PurchaseShip_FullMethodName                          = "/daemon.DaemonService/PurchaseShip"
	DaemonService_BatchPurchaseShips_FullMethodName                    = "/daemon.DaemonService/BatchPurchaseShips"
	DaemonService_GetShipyardListings_FullMethodName                   = "/daemon.DaemonService/GetShipyardListings"
	DaemonService_StartGoodsFactory_FullMethodName                     = "/daemon.DaemonService/StartGoodsFactory"
	DaemonService_StopGoodsFactory_FullMethodName                      = "/daemon.DaemonService/StopGoodsFactory"
	DaemonService_GetFactoryStatus_FullMethodName                      = "/daemon.DaemonService/GetFactoryStatus"
	DaemonService_ScanArbitrageOpportunities_FullMethodName            = "/daemon.DaemonService/ScanArbitrageOpportunities"
	DaemonService_StartArbitrageCoordinator_FullMethodName             = "/daemon.DaemonService/StartArbitrageCoordinator"
	DaemonService_StartParallelManufacturingCoordinator_FullMethodName = "/daemon.DaemonService/StartParallelManufacturingCoordinator"
	DaemonService_JettisonCargo_FullMethodName                         = "/daemon.DaemonService/JettisonCargo"
	DaemonService_GasExtractionOperation_FullMethodName                = "/daemon.DaemonService/GasExtractionOperation"
	DaemonService_StartTradeRoute_FullMethodName                       = "/daemon.DaemonService/StartTradeRoute"
	DaemonService_StartConstructionPipeline_FullMethodName             = "/daemon.DaemonService/StartConstructionPipeline"
	DaemonService_GetConstructionStatus_FullMethodName                 = "/daemon.DaemonService/GetConstructionStatus"
	DaemonService_StopConstructionPipeline_FullMethodName              = "/daemon.DaemonService/StopConstructionPipeline"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService defines the gRPC API for CLI <-> Daemon communication
// Communication occurs over Unix domain socket for security and performance
type DaemonServiceClient interface {
	// NavigateShip initiates a ship navigation operation as a background container
	NavigateShip(ctx context.Context, in *NavigateShipRequest, opts ...grpc.CallOption) (*NavigateShipResponse, error)
	// DockShip docks a ship at its current location
	DockShip(ctx context.Context, in *DockShipRequest, opts ...grpc.CallOption) (*DockShipResponse, error)
	// OrbitShip puts a ship into orbit from docked position
	OrbitShip(ctx context.Context, in *OrbitShipRequest, opts ...grpc.CallOption) (*OrbitShipResponse, error)
	// RefuelShip refuels a ship at its current location
	RefuelShip(ctx context.Context, in *RefuelShipRequest, opts ...grpc.CallOption) (*RefuelShipResponse, error)
	// JumpShip executes a jump to a different star system via jump gate
	JumpShip(ctx context.Context, in *JumpShipRequest, opts ...grpc.CallOption) (*JumpShipResponse, error)
	// BatchContractWorkflow executes batch contract workflow operations
	BatchContractWorkflow(ctx context.Context, in *BatchContractWorkflowRequest, opts ...grpc.CallOption) (*BatchContractWorkflowResponse, error)
	// ContractFleetCoordinator manages a pool of ships for continuous contract execution
	ContractFleetCoordinator(ctx context.Context, in *ContractFleetCoordinatorRequest, opts ...grpc.CallOption) (*ContractFleetCoordinatorResponse, error)
	// ScoutTour executes market scouting tour operations (single ship)
	ScoutTour(ctx context.Context, in *ScoutTourRequest, opts ...grpc.CallOption) (*ScoutTourResponse, error)
	// ScoutMarkets orchestrates fleet deployment for market scouting (multi-ship with VRP)
	ScoutMarkets(ctx context.Context, in *ScoutMarketsRequest, opts ...grpc.CallOption) (*ScoutMarketsResponse, error)
	// AssignScoutingFleet auto-discovers probe/satellite ships and assigns them to scout markets
	AssignScoutingFleet(ctx context.Context, in *AssignScoutingFleetRequest, opts ...grpc.CallOption) (*AssignScoutingFleetResponse, error)
	// ListContainers returns all running background containers
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	// GetContainer returns detailed information about a specific container
	GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error)
	// StopContainer stops a running background container
	StopContainer(ctx context.Context, in *StopContainerRequest, opts ...grpc.CallOption) (*StopContainerResponse, error)
	// GetContainerLogs retrieves logs from a container
	GetContainerLogs(ctx context.Context, in *GetContainerLogsRequest, opts ...grpc.CallOption) (*GetContainerLogsResponse, error)
	// HealthCheck verifies daemon is running and responsive
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// GetAPIBudget returns API request-budget observability (sp-51ti):
	// per-hull req/s, global utilization vs the rate ceiling (429 rate, poll
	// cadence share of the budget, headroom), and the duty-cycle KPI
	// (ship-hours earning/day per hull).
	GetAPIBudget(ctx context.Context, in *GetAPIBudgetRequest, opts ...grpc.CallOption) (*GetAPIBudgetResponse, error)
	// ListShips returns all ships for a player
	ListShips(ctx context.Context, in *ListShipsRequest, opts ...grpc.CallOption) (*ListShipsResponse, error)
	// GetShip returns detailed information about a specific ship
	GetShip(ctx context.Context, in *GetShipRequest, opts ...grpc.CallOption) (*GetShipResponse, error)
	// RefreshShip forces a resync of a ship from the API, overwriting the cache
	RefreshShip(ctx context.Context, in *RefreshShipRequest, opts ...grpc.CallOption) (*RefreshShipResponse, error)
	// ReserveShip reserves a ship for the captain's direct manual use, hiding
	// it from every coordinator's assignment discovery (sp-i1ku)
	ReserveShip(ctx context.Context, in *ReserveShipRequest, opts ...grpc.CallOption) (*ReserveShipResponse, error)
	// ReleaseShip clears a captain reservation, returning the ship to idle so
	// normal coordinator discovery can claim it again (sp-i1ku)
	ReleaseShip(ctx context.Context, in *ReleaseShipRequest, opts ...grpc.CallOption) (*ReleaseShipResponse, error)
	// AssignShipFleet dedicates a ship to a named fleet, making it exclusive
	// to that fleet's coordinator (sp-l7h2)
	AssignShipFleet(ctx context.Context, in *AssignShipFleetRequest, opts ...grpc.CallOption) (*AssignShipFleetResponse, error)
	// UnassignShipFleet clears a ship's fleet dedication, returning it to the
	// general pool (sp-l7h2)
	UnassignShipFleet(ctx context.Context, in *UnassignShipFleetRequest, opts ...grpc.CallOption) (*UnassignShipFleetResponse, error)
	// ListFleets lists every dedicated fleet and its member ships (sp-l7h2)
	ListFleets(ctx context.Context, in *ListFleetsRequest, opts ...grpc.CallOption) (*ListFleetsResponse, error)
	// ListWaypoints lists the waypoints of a system from the daemon's waypoint cache
	ListWaypoints(ctx context.Context, in *ListWaypointsRequest, opts ...grpc.CallOption) (*ListWaypointsResponse, error)
	// GetWaypoint returns the detail of a single waypoint
	GetWaypoint(ctx context.Context, in *GetWaypointRequest, opts ...grpc.CallOption) (*GetWaypointResponse, error)
	// PurchaseShip purchases a single ship from a shipyard
	PurchaseShip(ctx context.Context, in *PurchaseShipRequest, opts ...grpc.CallOption) (*PurchaseShipResponse, error)
	// BatchPurchaseShips purchases multiple ships from a shipyard as a background operation
	BatchPurchaseShips(ctx context.Context, in *BatchPurchaseShipsRequest, opts ...grpc.CallOption) (*BatchPurchaseShipsResponse, error)
	// GetShipyardListings retrieves available ships at a shipyard
	GetShipyardListings(ctx context.Context, in *GetShipyardListingsRequest, opts ...grpc.CallOption) (*GetShipyardListingsResponse, error)
	// StartGoodsFactory initiates automated goods production using supply chain fabrication
	StartGoodsFactory(ctx context.Context, in *StartGoodsFactoryRequest, opts ...grpc.CallOption) (*StartGoodsFactoryResponse, error)
	// StopGoodsFactory stops a running goods factory operation
	StopGoodsFactory(ctx context.Context, in *StopGoodsFactoryRequest, opts ...grpc.CallOption) (*StopGoodsFactoryResponse, error)
	// GetFactoryStatus retrieves status and progress of a goods factory
	GetFactoryStatus(ctx context.Context, in *GetFactoryStatusRequest, opts ...grpc.CallOption) (*GetFactoryStatusResponse, error)
	// ScanArbitrageOpportunities scans markets for profitable arbitrage opportunities
	ScanArbitrageOpportunities(ctx context.Context, in *ScanArbitrageOpportunitiesRequest, opts ...grpc.CallOption) (*ScanArbitrageOpportunitiesResponse, error)
	// StartArbitrageCoordinator initiates automated arbitrage trading operations
	StartArbitrageCoordinator(ctx context.Context, in *StartArbitrageCoordinatorRequest, opts ...grpc.CallOption) (*StartArbitrageCoordinatorResponse, error)
	// StartParallelManufacturingCoordinator initiates parallel task-based manufacturing operations
	StartParallelManufacturingCoordinator(ctx context.Context, in *StartParallelManufacturingCoordinatorRequest, opts ...grpc.CallOption) (*StartParallelManufacturingCoordinatorResponse, error)
	// JettisonCargo jettisons cargo from a ship
	JettisonCargo(ctx context.Context, in *JettisonCargoRequest, opts ...grpc.CallOption) (*JettisonCargoResponse, error)
	// GasExtractionOperation starts a gas extraction operation with siphon and transport ships
	GasExtractionOperation(ctx context.Context, in *GasExtractionOperationRequest, opts ...grpc.CallOption) (*GasExtractionOperationResponse, error)
	// StartTradeRoute launches a single-hull pure-arbitrage circuit as a recovery-safe daemon container
	StartTradeRoute(ctx context.Context, in *StartTradeRouteRequest, opts ...grpc.CallOption) (*StartTradeRouteResponse, error)
	// StartConstructionPipeline starts a pipeline to supply materials to a construction site
	StartConstructionPipeline(ctx context.Context, in *StartConstructionPipelineRequest, opts ...grpc.CallOption) (*StartConstructionPipelineResponse, error)
	// GetConstructionStatus retrieves the status of a construction site
	GetConstructionStatus(ctx context.Context, in *GetConstructionStatusRequest, opts ...grpc.CallOption) (*GetConstructionStatusResponse, error)
	// StopConstructionPipeline cancels the active construction pipeline for a site (sp-yzrv)
	StopConstructionPipeline(ctx context.Context, in *StopConstructionPipelineRequest, opts ...grpc.CallOption) (*StopConstructionPipelineResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) NavigateShip(ctx context.Context, in *NavigateShipRequest, opts ...grpc.CallOption) (*NavigateShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_NavigateShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DockShip(ctx context.Context, in *DockShipRequest, opts ...grpc.CallOption) (*DockShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_DockShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) OrbitShip(ctx context.Context, in *OrbitShipRequest, opts ...grpc.CallOption) (*OrbitShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrbitShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_OrbitShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RefuelShip(ctx context.Context, in *RefuelShipRequest, opts ...grpc.CallOption) (*RefuelShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefuelShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_RefuelShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) JumpShip(ctx context.Context, in *JumpShipRequest, opts ...grpc.CallOption) (*JumpShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JumpShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_JumpShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) BatchContractWorkflow(ctx context.Context, in *BatchContractWorkflowRequest, opts ...grpc.CallOption) (*BatchContractWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchContractWorkflowResponse)
	err := c.cc.Invoke(ctx, DaemonService_BatchContractWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ContractFleetCoordinator(ctx context.Context, in *ContractFleetCoordinatorRequest, opts ...grpc.CallOption) (*ContractFleetCoordinatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractFleetCoordinatorResponse)
	err := c.cc.Invoke(ctx, DaemonService_ContractFleetCoordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ScoutTour(ctx context.Context, in *ScoutTourRequest, opts ...grpc.CallOption) (*ScoutTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoutTourResponse)
	err := c.cc.Invoke(ctx, DaemonService_ScoutTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ScoutMarkets(ctx context.Context, in *ScoutMarketsRequest, opts ...grpc.CallOption) (*ScoutMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoutMarketsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ScoutMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) AssignScoutingFleet(ctx context.Context, in *AssignScoutingFleetRequest, opts ...grpc.CallOption) (*AssignScoutingFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignScoutingFleetResponse)
	err := c.cc.Invoke(ctx, DaemonService_AssignScoutingFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContainersResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopContainer(ctx context.Context, in *StopContainerRequest, opts ...grpc.CallOption) (*StopContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopContainerResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetContainerLogs(ctx context.Context, in *GetContainerLogsRequest, opts ...grpc.CallOption) (*GetContainerLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerLogsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetContainerLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DaemonService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetAPIBudget(ctx context.Context, in *GetAPIBudgetRequest, opts ...grpc.CallOption) (*GetAPIBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAPIBudgetResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetAPIBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListShips(ctx context.Context, in *ListShipsRequest, opts ...grpc.CallOption) (*ListShipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShipsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListShips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetShip(ctx context.Context, in *GetShipRequest, opts ...grpc.CallOption) (*GetShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RefreshShip(ctx context.Context, in *RefreshShipRequest, opts ...grpc.CallOption) (*RefreshShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_RefreshShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ReserveShip(ctx context.Context, in *ReserveShipRequest, opts ...grpc.CallOption) (*ReserveShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_ReserveShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ReleaseShip(ctx context.Context, in *ReleaseShipRequest, opts ...grpc.CallOption) (*ReleaseShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_ReleaseShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) AssignShipFleet(ctx context.Context, in *AssignShipFleetRequest, opts ...grpc.CallOption) (*AssignShipFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignShipFleetResponse)
	err := c.cc.Invoke(ctx, DaemonService_AssignShipFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UnassignShipFleet(ctx context.Context, in *UnassignShipFleetRequest, opts ...grpc.CallOption) (*UnassignShipFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignShipFleetResponse)
	err := c.cc.Invoke(ctx, DaemonService_UnassignShipFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListFleets(ctx context.Context, in *ListFleetsRequest, opts ...grpc.CallOption) (*ListFleetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFleetsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListFleets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListWaypoints(ctx context.Context, in *ListWaypointsRequest, opts ...grpc.CallOption) (*ListWaypointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWaypointsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListWaypoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetWaypoint(ctx context.Context, in *GetWaypointRequest, opts ...grpc.CallOption) (*GetWaypointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWaypointResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetWaypoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) PurchaseShip(ctx context.Context, in *PurchaseShipRequest, opts ...grpc.CallOption) (*PurchaseShipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseShipResponse)
	err := c.cc.Invoke(ctx, DaemonService_PurchaseShip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) BatchPurchaseShips(ctx context.Context, in *BatchPurchaseShipsRequest, opts ...grpc.CallOption) (*BatchPurchaseShipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPurchaseShipsResponse)
	err := c.cc.Invoke(ctx, DaemonService_BatchPurchaseShips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetShipyardListings(ctx context.Context, in *GetShipyardListingsRequest, opts ...grpc.CallOption) (*GetShipyardListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShipyardListingsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetShipyardListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartGoodsFactory(ctx context.Context, in *StartGoodsFactoryRequest, opts ...grpc.CallOption) (*StartGoodsFactoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGoodsFactoryResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartGoodsFactory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopGoodsFactory(ctx context.Context, in *StopGoodsFactoryRequest, opts ...grpc.CallOption) (*StopGoodsFactoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopGoodsFactoryResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopGoodsFactory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetFactoryStatus(ctx context.Context, in *GetFactoryStatusRequest, opts ...grpc.CallOption) (*GetFactoryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFactoryStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetFactoryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ScanArbitrageOpportunities(ctx context.Context, in *ScanArbitrageOpportunitiesRequest, opts ...grpc.CallOption) (*ScanArbitrageOpportunitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanArbitrageOpportunitiesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ScanArbitrageOpportunities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartArbitrageCoordinator(ctx context.Context, in *StartArbitrageCoordinatorRequest, opts ...grpc.CallOption) (*StartArbitrageCoordinatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartArbitrageCoordinatorResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartArbitrageCoordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartParallelManufacturingCoordinator(ctx context.Context, in *StartParallelManufacturingCoordinatorRequest, opts ...grpc.CallOption) (*StartParallelManufacturingCoordinatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartParallelManufacturingCoordinatorResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartParallelManufacturingCoordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) JettisonCargo(ctx context.Context, in *JettisonCargoRequest, opts ...grpc.CallOption) (*JettisonCargoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JettisonCargoResponse)
	err := c.cc.Invoke(ctx, DaemonService_JettisonCargo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GasExtractionOperation(ctx context.Context, in *GasExtractionOperationRequest, opts ...grpc.CallOption) (*GasExtractionOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GasExtractionOperationResponse)
	err := c.cc.Invoke(ctx, DaemonService_GasExtractionOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartTradeRoute(ctx context.Context, in *StartTradeRouteRequest, opts ...grpc.CallOption) (*StartTradeRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTradeRouteResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartTradeRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartConstructionPipeline(ctx context.Context, in *StartConstructionPipelineRequest, opts ...grpc.CallOption) (*StartConstructionPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartConstructionPipelineResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartConstructionPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetConstructionStatus(ctx context.Context, in *GetConstructionStatusRequest, opts ...grpc.CallOption) (*GetConstructionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConstructionStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetConstructionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopConstructionPipeline(ctx context.Context, in *StopConstructionPipelineRequest, opts ...grpc.CallOption) (*StopConstructionPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopConstructionPipelineResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopConstructionPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService defines the gRPC API for CLI <-> Daemon communication
// Communication occurs over Unix domain socket for security and performance
type DaemonServiceServer interface {
	// NavigateShip initiates a ship navigation operation as a background container
	NavigateShip(context.Context, *NavigateShipRequest) (*NavigateShipResponse, error)
	// DockShip docks a ship at its current location
	DockShip(context.Context, *DockShipRequest) (*DockShipResponse, error)
	// OrbitShip puts a ship into orbit from docked position
	OrbitShip(context.Context, *OrbitShipRequest) (*OrbitShipResponse, error)
	// RefuelShip refuels a ship at its current location
	RefuelShip(context.Context, *RefuelShipRequest) (*RefuelShipResponse, error)
	// JumpShip executes a jump to a different star system via jump gate
	JumpShip(context.Context, *JumpShipRequest) (*JumpShipResponse, error)
	// BatchContractWorkflow executes batch contract workflow operations
	BatchContractWorkflow(context.Context, *BatchContractWorkflowRequest) (*BatchContractWorkflowResponse, error)
	// ContractFleetCoordinator manages a pool of ships for continuous contract execution
	ContractFleetCoordinator(context.Context, *ContractFleetCoordinatorRequest) (*ContractFleetCoordinatorResponse, error)
	// ScoutTour executes market scouting tour operations (single ship)
	ScoutTour(context.Context, *ScoutTourRequest) (*ScoutTourResponse, error)
	// ScoutMarkets orchestrates fleet deployment for market scouting (multi-ship with VRP)
	ScoutMarkets(context.Context, *ScoutMarketsRequest) (*ScoutMarketsResponse, error)
	// AssignScoutingFleet auto-discovers probe/satellite ships and assigns them to scout markets
	AssignScoutingFleet(context.Context, *AssignScoutingFleetRequest) (*AssignScoutingFleetResponse, error)
	// ListContainers returns all running background containers
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	// GetContainer returns detailed information about a specific container
	GetContainer(context.Context, *GetContainerRequest) (*GetContainerResponse, error)
	// StopContainer stops a running background container
	StopContainer(context.Context, *StopContainerRequest) (*StopContainerResponse, error)
	// GetContainerLogs retrieves logs from a container
	GetContainerLogs(context.Context, *GetContainerLogsRequest) (*GetContainerLogsResponse, error)
	// HealthCheck verifies daemon is running and responsive
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// GetAPIBudget returns API request-budget observability (sp-51ti):
	// per-hull req/s, global utilization vs the rate ceiling (429 rate, poll
	// cadence share of the budget, headroom), and the duty-cycle KPI
	// (ship-hours earning/day per hull).
	GetAPIBudget(context.Context, *GetAPIBudgetRequest) (*GetAPIBudgetResponse, error)
	// ListShips returns all ships for a player
	ListShips(context.Context, *ListShipsRequest) (*ListShipsResponse, error)
	// GetShip returns detailed information about a specific ship
	GetShip(context.Context, *GetShipRequest) (*GetShipResponse, error)
	// RefreshShip forces a resync of a ship from the API, overwriting the cache
	RefreshShip(context.Context, *RefreshShipRequest) (*RefreshShipResponse, error)
	// ReserveShip reserves a ship for the captain's direct manual use, hiding
	// it from every coordinator's assignment discovery (sp-i1ku)
	ReserveShip(context.Context, *ReserveShipRequest) (*ReserveShipResponse, error)
	// ReleaseShip clears a captain reservation, returning the ship to idle so
	// normal coordinator discovery can claim it again (sp-i1ku)
	ReleaseShip(context.Context, *ReleaseShipRequest) (*ReleaseShipResponse, error)
	// AssignShipFleet dedicates a ship to a named fleet, making it exclusive
	// to that fleet's coordinator (sp-l7h2)
	AssignShipFleet(context.Context, *AssignShipFleetRequest) (*AssignShipFleetResponse, error)
	// UnassignShipFleet clears a ship's fleet dedication, returning it to the
	// general pool (sp-l7h2)
	UnassignShipFleet(context.Context, *UnassignShipFleetRequest) (*UnassignShipFleetResponse, error)
	// ListFleets lists every dedicated fleet and its member ships (sp-l7h2)
	ListFleets(context.Context, *ListFleetsRequest) (*ListFleetsResponse, error)
	// ListWaypoints lists the waypoints of a system from the daemon's waypoint cache
	ListWaypoints(context.Context, *ListWaypointsRequest) (*ListWaypointsResponse, error)
	// GetWaypoint returns the detail of a single waypoint
	GetWaypoint(context.Context, *GetWaypointRequest) (*GetWaypointResponse, error)
	// PurchaseShip purchases a single ship from a shipyard
	PurchaseShip(context.Context, *PurchaseShipRequest) (*PurchaseShipResponse, error)
	// BatchPurchaseShips purchases multiple ships from a shipyard as a background operation
	BatchPurchaseShips(context.Context, *BatchPurchaseShipsRequest) (*BatchPurchaseShipsResponse, error)
	// GetShipyardListings retrieves available ships at a shipyard
	GetShipyardListings(context.Context, *GetShipyardListingsRequest) (*GetShipyardListingsResponse, error)
	// StartGoodsFactory initiates automated goods production using supply chain fabrication
	StartGoodsFactory(context.Context, *StartGoodsFactoryRequest) (*StartGoodsFactoryResponse, error)
	// StopGoodsFactory stops a running goods factory operation
	StopGoodsFactory(context.Context, *StopGoodsFactoryRequest) (*StopGoodsFactoryResponse, error)
	// GetFactoryStatus retrieves status and progress of a goods factory
	GetFactoryStatus(context.Context, *GetFactoryStatusRequest) (*GetFactoryStatusResponse, error)
	// ScanArbitrageOpportunities scans markets for profitable arbitrage opportunities
	ScanArbitrageOpportunities(context.Context, *ScanArbitrageOpportunitiesRequest) (*ScanArbitrageOpportunitiesResponse, error)
	// StartArbitrageCoordinator initiates automated arbitrage trading operations
	StartArbitrageCoordinator(context.Context, *StartArbitrageCoordinatorRequest) (*StartArbitrageCoordinatorResponse, error)
	// StartParallelManufacturingCoordinator initiates parallel task-based manufacturing operations
	StartParallelManufacturingCoordinator(context.Context, *StartParallelManufacturingCoordinatorRequest) (*StartParallelManufacturingCoordinatorResponse, error)
	// JettisonCargo jettisons cargo from a ship
	JettisonCargo(context.Context, *JettisonCargoRequest) (*JettisonCargoResponse, error)
	// GasExtractionOperation starts a gas extraction operation with siphon and transport ships
	GasExtractionOperation(context.Context, *GasExtractionOperationRequest) (*GasExtractionOperationResponse, error)
	// StartTradeRoute launches a single-hull pure-arbitrage circuit as a recovery-safe daemon container
	StartTradeRoute(context.Context, *StartTradeRouteRequest) (*StartTradeRouteResponse, error)
	// StartConstructionPipeline starts a pipeline to supply materials to a construction site
	StartConstructionPipeline(context.Context, *StartConstructionPipelineRequest) (*StartConstructionPipelineResponse, error)
	// GetConstructionStatus retrieves the status of a construction site
	GetConstructionStatus(context.Context, *GetConstructionStatusRequest) (*GetConstructionStatusResponse, error)
	// StopConstructionPipeline cancels the active construction pipeline for a site (sp-yzrv)
	StopConstructionPipeline(context.Context, *StopConstructionPipelineRequest) (*StopConstructionPipelineResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) NavigateShip(context.Context, *NavigateShipRequest) (*NavigateShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NavigateShip not implemented")
}
func (UnimplementedDaemonServiceServer) DockShip(context.Context, *DockShipRequest) (*DockShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DockShip not implemented")
}
func (UnimplementedDaemonServiceServer) OrbitShip(context.Context, *OrbitShipRequest) (*OrbitShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OrbitShip not implemented")
}
func (UnimplementedDaemonServiceServer) RefuelShip(context.Context, *RefuelShipRequest) (*RefuelShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefuelShip not implemented")
}
func (UnimplementedDaemonServiceServer) JumpShip(context.Context, *JumpShipRequest) (*JumpShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JumpShip not implemented")
}
func (UnimplementedDaemonServiceServer) BatchContractWorkflow(context.Context, *BatchContractWorkflowRequest) (*BatchContractWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchContractWorkflow not implemented")
}
func (UnimplementedDaemonServiceServer) ContractFleetCoordinator(context.Context, *ContractFleetCoordinatorRequest) (*ContractFleetCoordinatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContractFleetCoordinator not implemented")
}
func (UnimplementedDaemonServiceServer) ScoutTour(context.Context, *ScoutTourRequest) (*ScoutTourResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoutTour not implemented")
}
func (UnimplementedDaemonServiceServer) ScoutMarkets(context.Context, *ScoutMarketsRequest) (*ScoutMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoutMarkets not implemented")
}
func (UnimplementedDaemonServiceServer) AssignScoutingFleet(context.Context, *AssignScoutingFleetRequest) (*AssignScoutingFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignScoutingFleet not implemented")
}
func (UnimplementedDaemonServiceServer) ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedDaemonServiceServer) GetContainer(context.Context, *GetContainerRequest) (*GetContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainer not implemented")
}
func (UnimplementedDaemonServiceServer) StopContainer(context.Context, *StopContainerRequest) (*StopContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopContainer not implemented")
}
func (UnimplementedDaemonServiceServer) GetContainerLogs(context.Context, *GetContainerLogsRequest) (*GetContainerLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainerLogs not implemented")
}
func (UnimplementedDaemonServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDaemonServiceServer) GetAPIBudget(context.Context, *GetAPIBudgetRequest) (*GetAPIBudgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAPIBudget not implemented")
}
func (UnimplementedDaemonServiceServer) ListShips(context.Context, *ListShipsRequest) (*ListShipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShips not implemented")
}
func (UnimplementedDaemonServiceServer) GetShip(context.Context, *GetShipRequest) (*GetShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShip not implemented")
}
func (UnimplementedDaemonServiceServer) RefreshShip(context.Context, *RefreshShipRequest) (*RefreshShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshShip not implemented")
}
func (UnimplementedDaemonServiceServer) ReserveShip(context.Context, *ReserveShipRequest) (*ReserveShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveShip not implemented")
}
func (UnimplementedDaemonServiceServer) ReleaseShip(context.Context, *ReleaseShipRequest) (*ReleaseShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseShip not implemented")
}
func (UnimplementedDaemonServiceServer) AssignShipFleet(context.Context, *AssignShipFleetRequest) (*AssignShipFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignShipFleet not implemented")
}
func (UnimplementedDaemonServiceServer) UnassignShipFleet(context.Context, *UnassignShipFleetRequest) (*UnassignShipFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnassignShipFleet not implemented")
}
func (UnimplementedDaemonServiceServer) ListFleets(context.Context, *ListFleetsRequest) (*ListFleetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFleets not implemented")
}
func (UnimplementedDaemonServiceServer) ListWaypoints(context.Context, *ListWaypointsRequest) (*ListWaypointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWaypoints not implemented")
}
func (UnimplementedDaemonServiceServer) GetWaypoint(context.Context, *GetWaypointRequest) (*GetWaypointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWaypoint not implemented")
}
func (UnimplementedDaemonServiceServer) PurchaseShip(context.Context, *PurchaseShipRequest) (*PurchaseShipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseShip not implemented")
}
func (UnimplementedDaemonServiceServer) BatchPurchaseShips(context.Context, *BatchPurchaseShipsRequest) (*BatchPurchaseShipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPurchaseShips not implemented")
}
func (UnimplementedDaemonServiceServer) GetShipyardListings(context.Context, *GetShipyardListingsRequest) (*GetShipyardListingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShipyardListings not implemented")
}
func (UnimplementedDaemonServiceServer) StartGoodsFactory(context.Context, *StartGoodsFactoryRequest) (*StartGoodsFactoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGoodsFactory not implemented")
}
func (UnimplementedDaemonServiceServer) StopGoodsFactory(context.Context, *StopGoodsFactoryRequest) (*StopGoodsFactoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopGoodsFactory not implemented")
}
func (UnimplementedDaemonServiceServer) GetFactoryStatus(context.Context, *GetFactoryStatusRequest) (*GetFactoryStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFactoryStatus not implemented")
}
func (UnimplementedDaemonServiceServer) ScanArbitrageOpportunities(context.Context, *ScanArbitrageOpportunitiesRequest) (*ScanArbitrageOpportunitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanArbitrageOpportunities not implemented")
}
func (UnimplementedDaemonServiceServer) StartArbitrageCoordinator(context.Context, *StartArbitrageCoordinatorRequest) (*StartArbitrageCoordinatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartArbitrageCoordinator not implemented")
}
func (UnimplementedDaemonServiceServer) StartParallelManufacturingCoordinator(context.Context, *StartParallelManufacturingCoordinatorRequest) (*StartParallelManufacturingCoordinatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartParallelManufacturingCoordinator not implemented")
}
func (UnimplementedDaemonServiceServer) JettisonCargo(context.Context, *JettisonCargoRequest) (*JettisonCargoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JettisonCargo not implemented")
}
func (UnimplementedDaemonServiceServer) GasExtractionOperation(context.Context, *GasExtractionOperationRequest) (*GasExtractionOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GasExtractionOperation not implemented")
}
func (UnimplementedDaemonServiceServer) StartTradeRoute(context.Context, *StartTradeRouteRequest) (*StartTradeRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTradeRoute not implemented")
}
func (UnimplementedDaemonServiceServer) StartConstructionPipeline(context.Context, *StartConstructionPipelineRequest) (*StartConstructionPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartConstructionPipeline not implemented")
}
func (UnimplementedDaemonServiceServer) GetConstructionStatus(context.Context, *GetConstructionStatusRequest) (*GetConstructionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConstructionStatus not implemented")
}
func (UnimplementedDaemonServiceServer) StopConstructionPipeline(context.Context, *StopConstructionPipelineRequest) (*StopConstructionPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopConstructionPipeline not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_NavigateShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).NavigateShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_NavigateShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).NavigateShip(ctx, req.(*NavigateShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DockShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DockShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DockShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DockShip(ctx, req.(*DockShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_OrbitShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrbitShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).OrbitShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_OrbitShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).OrbitShip(ctx, req.(*OrbitShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RefuelShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefuelShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RefuelShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RefuelShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RefuelShip(ctx, req.(*RefuelShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_JumpShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JumpShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).JumpShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_JumpShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).JumpShip(ctx, req.(*JumpShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_BatchContractWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchContractWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).BatchContractWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_BatchContractWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).BatchContractWorkflow(ctx, req.(*BatchContractWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ContractFleetCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractFleetCoordinatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ContractFleetCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ContractFleetCoordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ContractFleetCoordinator(ctx, req.(*ContractFleetCoordinatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ScoutTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoutTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ScoutTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ScoutTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ScoutTour(ctx, req.(*ScoutTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ScoutMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoutMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ScoutMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ScoutMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ScoutMarkets(ctx, req.(*ScoutMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_AssignScoutingFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignScoutingFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).AssignScoutingFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_AssignScoutingFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).AssignScoutingFleet(ctx, req.(*AssignScoutingFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetContainer(ctx, req.(*GetContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopContainer(ctx, req.(*StopContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetContainerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetContainerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetContainerLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetContainerLogs(ctx, req.(*GetContainerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetAPIBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPIBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetAPIBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetAPIBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetAPIBudget(ctx, req.(*GetAPIBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListShips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListShips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListShips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListShips(ctx, req.(*ListShipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetShip(ctx, req.(*GetShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RefreshShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RefreshShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RefreshShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RefreshShip(ctx, req.(*RefreshShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ReserveShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ReserveShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ReserveShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ReserveShip(ctx, req.(*ReserveShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ReleaseShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ReleaseShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ReleaseShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ReleaseShip(ctx, req.(*ReleaseShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_AssignShipFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignShipFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).AssignShipFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_AssignShipFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).AssignShipFleet(ctx, req.(*AssignShipFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UnassignShipFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignShipFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UnassignShipFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_UnassignShipFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UnassignShipFleet(ctx, req.(*UnassignShipFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListFleets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFleetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListFleets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListFleets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListFleets(ctx, req.(*ListFleetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListWaypoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWaypointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListWaypoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListWaypoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListWaypoints(ctx, req.(*ListWaypointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetWaypoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaypointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetWaypoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetWaypoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetWaypoint(ctx, req.(*GetWaypointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_PurchaseShip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).PurchaseShip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_PurchaseShip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).PurchaseShip(ctx, req.(*PurchaseShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_BatchPurchaseShips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPurchaseShipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).BatchPurchaseShips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_BatchPurchaseShips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).BatchPurchaseShips(ctx, req.(*BatchPurchaseShipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetShipyardListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipyardListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetShipyardListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetShipyardListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetShipyardListings(ctx, req.(*GetShipyardListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartGoodsFactory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGoodsFactoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartGoodsFactory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartGoodsFactory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartGoodsFactory(ctx, req.(*StartGoodsFactoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopGoodsFactory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopGoodsFactoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopGoodsFactory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopGoodsFactory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopGoodsFactory(ctx, req.(*StopGoodsFactoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetFactoryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFactoryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetFactoryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetFactoryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetFactoryStatus(ctx, req.(*GetFactoryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ScanArbitrageOpportunities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanArbitrageOpportunitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ScanArbitrageOpportunities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ScanArbitrageOpportunities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ScanArbitrageOpportunities(ctx, req.(*ScanArbitrageOpportunitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartArbitrageCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartArbitrageCoordinatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartArbitrageCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartArbitrageCoordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartArbitrageCoordinator(ctx, req.(*StartArbitrageCoordinatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartParallelManufacturingCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartParallelManufacturingCoordinatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartParallelManufacturingCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartParallelManufacturingCoordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartParallelManufacturingCoordinator(ctx, req.(*StartParallelManufacturingCoordinatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_JettisonCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JettisonCargoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).JettisonCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_JettisonCargo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).JettisonCargo(ctx, req.(*JettisonCargoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GasExtractionOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GasExtractionOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GasExtractionOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GasExtractionOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GasExtractionOperation(ctx, req.(*GasExtractionOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartTradeRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTradeRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartTradeRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartTradeRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartTradeRoute(ctx, req.(*StartTradeRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartConstructionPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartConstructionPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartConstructionPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartConstructionPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartConstructionPipeline(ctx, req.(*StartConstructionPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetConstructionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConstructionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetConstructionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetConstructionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetConstructionStatus(ctx, req.(*GetConstructionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopConstructionPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopConstructionPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopConstructionPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopConstructionPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopConstructionPipeline(ctx, req.(*StopConstructionPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NavigateShip",
			Handler:    _DaemonService_NavigateShip_Handler,
		},
		{
			MethodName: "DockShip",
			Handler:    _DaemonService_DockShip_Handler,
		},
		{
			MethodName: "OrbitShip",
			Handler:    _DaemonService_OrbitShip_Handler,
		},
		{
			MethodName: "RefuelShip",
			Handler:    _DaemonService_RefuelShip_Handler,
		},
		{
			MethodName: "JumpShip",
			Handler:    _DaemonService_JumpShip_Handler,
		},
		{
			MethodName: "BatchContractWorkflow",
			Handler:    _DaemonService_BatchContractWorkflow_Handler,
		},
		{
			MethodName: "ContractFleetCoordinator",
			Handler:    _DaemonService_ContractFleetCoordinator_Handler,
		},
		{
			MethodName: "ScoutTour",
			Handler:    _DaemonService_ScoutTour_Handler,
		},
		{
			MethodName: "ScoutMarkets",
			Handler:    _DaemonService_ScoutMarkets_Handler,
		},
		{
			MethodName: "AssignScoutingFleet",
			Handler:    _DaemonService_AssignScoutingFleet_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _DaemonService_ListContainers_Handler,
		},
		{
			MethodName: "GetContainer",
			Handler:    _DaemonService_GetContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _DaemonService_StopContainer_Handler,
		},
		{
			MethodName: "GetContainerLogs",
			Handler:    _DaemonService_GetContainerLogs_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DaemonService_HealthCheck_Handler,
		},
		{
			MethodName: "GetAPIBudget",
			Handler:    _DaemonService_GetAPIBudget_Handler,
		},
		{
			MethodName: "ListShips",
			Handler:    _DaemonService_ListShips_Handler,
		},
		{
			MethodName: "GetShip",
			Handler:    _DaemonService_GetShip_Handler,
		},
		{
			MethodName: "RefreshShip",
			Handler:    _DaemonService_RefreshShip_Handler,
		},
		{
			MethodName: "ReserveShip",
			Handler:    _DaemonService_ReserveShip_Handler,
		},
		{
			MethodName: "ReleaseShip",
			Handler:    _DaemonService_ReleaseShip_Handler,
		},
		{
			MethodName: "AssignShipFleet",
			Handler:    _DaemonService_AssignShipFleet_Handler,
		},
		{
			MethodName: "UnassignShipFleet",
			Handler:    _DaemonService_UnassignShipFleet_Handler,
		},
		{
			MethodName: "ListFleets",
			Handler:    _DaemonService_ListFleets_Handler,
		},
		{
			MethodName: "ListWaypoints",
			Handler:    _DaemonService_ListWaypoints_Handler,
		},
		{
			MethodName: "GetWaypoint",
			Handler:    _DaemonService_GetWaypoint_Handler,
		},
		{
			MethodName: "PurchaseShip",
			Handler:    _DaemonService_PurchaseShip_Handler,
		},
		{
			MethodName: "BatchPurchaseShips",
			Handler:    _DaemonService_BatchPurchaseShips_Handler,
		},
		{
			MethodName: "GetShipyardListings",
			Handler:    _DaemonService_GetShipyardListings_Handler,
		},
		{
			MethodName: "StartGoodsFactory",
			Handler:    _DaemonService_StartGoodsFactory_Handler,
		},
		{
			MethodName: "StopGoodsFactory",
			Handler:    _DaemonService_StopGoodsFactory_Handler,
		},
		{
			MethodName: "GetFactoryStatus",
			Handler:    _DaemonService_GetFactoryStatus_Handler,
		},
		{
			MethodName: "ScanArbitrageOpportunities",
			Handler:    _DaemonService_ScanArbitrageOpportunities_Handler,
		},
		{
			MethodName: "StartArbitrageCoordinator",
			Handler:    _DaemonService_StartArbitrageCoordinator_Handler,
		},
		{
			MethodName: "StartParallelManufacturingCoordinator",
			Handler:    _DaemonService_StartParallelManufacturingCoordinator_Handler,
		},
		{
			MethodName: "JettisonCargo",
			Handler:    _DaemonService_JettisonCargo_Handler,
		},
		{
			MethodName: "GasExtractionOperation",
			Handler:    _DaemonService_GasExtractionOperation_Handler,
		},
		{
			MethodName: "StartTradeRoute",
			Handler:    _DaemonService_StartTradeRoute_Handler,
		},
		{
			MethodName: "StartConstructionPipeline",
			Handler:    _DaemonService_StartConstructionPipeline_Handler,
		},
		{
			MethodName: "GetConstructionStatus",
			Handler:    _DaemonService_GetConstructionStatus_Handler,
		},
		{
			MethodName: "StopConstructionPipeline",
			Handler:    _DaemonService_StopConstructionPipeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/daemon/daemon.proto",
}
