// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pkg/proto/routing/routing.proto

package routing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutingService_PlanRoute_FullMethodName          = "/routing.RoutingService/PlanRoute"
	RoutingService_OptimizeTour_FullMethodName       = "/routing.RoutingService/OptimizeTour"
	RoutingService_OptimizeFueledTour_FullMethodName = "/routing.RoutingService/OptimizeFueledTour"
	RoutingService_PartitionFleet_FullMethodName     = "/routing.RoutingService/PartitionFleet"
)

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoutingService defines the gRPC API for Daemon <-> OR-Tools communication
// Provides route planning, TSP optimization, and VRP fleet partitioning
// This service runs as a separate Python process using OR-Tools library
type RoutingServiceClient interface {
	// PlanRoute computes optimal route with fuel constraints using Dijkstra
	PlanRoute(ctx context.Context, in *PlanRouteRequest, opts ...grpc.CallOption) (*PlanRouteResponse, error)
	// OptimizeTour solves TSP for visiting multiple waypoints optimally
	OptimizeTour(ctx context.Context, in *OptimizeTourRequest, opts ...grpc.CallOption) (*OptimizeTourResponse, error)
	// OptimizeFueledTour solves TSP with global fuel optimization
	// Returns visit order + flight modes + refuel stops to minimize total travel time
	OptimizeFueledTour(ctx context.Context, in *OptimizeFueledTourRequest, opts ...grpc.CallOption) (*OptimizeFueledTourResponse, error)
	// PartitionFleet solves VRP to distribute waypoints across multiple ships
	PartitionFleet(ctx context.Context, in *PartitionFleetRequest, opts ...grpc.CallOption) (*PartitionFleetResponse, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) PlanRoute(ctx context.Context, in *PlanRouteRequest, opts ...grpc.CallOption) (*PlanRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanRouteResponse)
	err := c.cc.Invoke(ctx, RoutingService_PlanRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) OptimizeTour(ctx context.Context, in *OptimizeTourRequest, opts ...grpc.CallOption) (*OptimizeTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeTourResponse)
	err := c.cc.Invoke(ctx, RoutingService_OptimizeTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) OptimizeFueledTour(ctx context.Context, in *OptimizeFueledTourRequest, opts ...grpc.CallOption) (*OptimizeFueledTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeFueledTourResponse)
	err := c.cc.Invoke(ctx, RoutingService_OptimizeFueledTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) PartitionFleet(ctx context.Context, in *PartitionFleetRequest, opts ...grpc.CallOption) (*PartitionFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionFleetResponse)
	err := c.cc.Invoke(ctx, RoutingService_PartitionFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations must embed UnimplementedRoutingServiceServer
// for forward compatibility.
//
// RoutingService defines the gRPC API for Daemon <-> OR-Tools communication
// Provides route planning, TSP optimization, and VRP fleet partitioning
// This service runs as a separate Python process using OR-Tools library
type RoutingServiceServer interface {
	// PlanRoute computes optimal route with fuel constraints using Dijkstra
	PlanRoute(context.Context, *PlanRouteRequest) (*PlanRouteResponse, error)
	// OptimizeTour solves TSP for visiting multiple waypoints optimally
	OptimizeTour(context.Context, *OptimizeTourRequest) (*OptimizeTourResponse, error)
	// OptimizeFueledTour solves TSP with global fuel optimization
	// Returns visit order + flight modes + refuel stops to minimize total travel time
	OptimizeFueledTour(context.Context, *OptimizeFueledTourRequest) (*OptimizeFueledTourResponse, error)
	// PartitionFleet solves VRP to distribute waypoints across multiple ships
	PartitionFleet(context.Context, *PartitionFleetRequest) (*PartitionFleetResponse, error)
	mustEmbedUnimplementedRoutingServiceServer()
}

// UnimplementedRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceServer struct{}

func (UnimplementedRoutingServiceServer) PlanRoute(context.Context, *PlanRouteRequest) (*PlanRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanRoute not implemented")
}
func (UnimplementedRoutingServiceServer) OptimizeTour(context.Context, *OptimizeTourRequest) (*OptimizeTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptimizeTour not implemented")
}
func (UnimplementedRoutingServiceServer) OptimizeFueledTour(context.Context, *OptimizeFueledTourRequest) (*OptimizeFueledTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptimizeFueledTour not implemented")
}
func (UnimplementedRoutingServiceServer) PartitionFleet(context.Context, *PartitionFleetRequest) (*PartitionFleetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartitionFleet not implemented")
}
func (UnimplementedRoutingServiceServer) mustEmbedUnimplementedRoutingServiceServer() {}
func (UnimplementedRoutingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_PlanRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).PlanRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_PlanRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).PlanRoute(ctx, req.(*PlanRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_OptimizeTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).OptimizeTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_OptimizeTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).OptimizeTour(ctx, req.(*OptimizeTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_OptimizeFueledTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeFueledTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).OptimizeFueledTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_OptimizeFueledTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).OptimizeFueledTour(ctx, req.(*OptimizeFueledTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_PartitionFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).PartitionFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_PartitionFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).PartitionFleet(ctx, req.(*PartitionFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routing.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlanRoute",
			Handler:    _RoutingService_PlanRoute_Handler,
		},
		{
			MethodName: "OptimizeTour",
			Handler:    _RoutingService_OptimizeTour_Handler,
		},
		{
			MethodName: "OptimizeFueledTour",
			Handler:    _RoutingService_OptimizeFueledTour_Handler,
		},
		{
			MethodName: "PartitionFleet",
			Handler:    _RoutingService_PartitionFleet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/routing/routing.proto",
}
