package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/spf13/cobra/doc"
	"github.com/stretchr/testify/require"
)

// TestGenManTreeProducesFiles is a smoke test, not a golden-file test: it
// asserts GenManTree runs over the real root command without error and
// produces output, not the exact rendered content (which would make every
// command's Short/Long text a change here).
func TestGenManTreeProducesFiles(t *testing.T) {
	dir := t.TempDir()

	header := &doc.GenManHeader{Title: "SPACETRADERS", Section: "1"}
	err := doc.GenManTree(NewRootCommand(), header, dir)
	require.NoError(t, err)

	entries, err := os.ReadDir(dir)
	require.NoError(t, err)
	require.NotEmpty(t, entries, "GenManTree must produce at least one man page")

	require.FileExists(t, filepath.Join(dir, "spacetraders-ship-list.1"),
		"a known leaf command must have a generated man page")
}

// TestGenManTreeHidesDocsCommand confirms the hidden `docs` command itself
// (Hidden: true in NewDocsCommand) does not appear in its own output — it
// documents the tree, so it must not pollute the tree it documents.
func TestGenManTreeHidesDocsCommand(t *testing.T) {
	dir := t.TempDir()

	err := doc.GenManTree(NewRootCommand(), &doc.GenManHeader{Title: "SPACETRADERS", Section: "1"}, dir)
	require.NoError(t, err)

	require.NoFileExists(t, filepath.Join(dir, "spacetraders-docs.1"))
	require.NoFileExists(t, filepath.Join(dir, "spacetraders-docs-man.1"))
}

// TestGenMarkdownTreeProducesFiles mirrors TestGenManTreeProducesFiles for
// the markdown reference generator.
func TestGenMarkdownTreeProducesFiles(t *testing.T) {
	dir := t.TempDir()

	err := doc.GenMarkdownTree(NewRootCommand(), dir)
	require.NoError(t, err)

	entries, err := os.ReadDir(dir)
	require.NoError(t, err)
	require.NotEmpty(t, entries, "GenMarkdownTree must produce at least one markdown file")

	require.FileExists(t, filepath.Join(dir, "spacetraders_ship_list.md"),
		"a known leaf command must have a generated markdown page")
}

// TestDocsCommandHiddenFromHelp confirms `docs` does not clutter
// `spacetraders --help` (the surface it exists to document) while remaining
// directly invokable — same contract as any other hidden cobra command.
func TestDocsCommandHiddenFromHelp(t *testing.T) {
	root := NewRootCommand()

	var found *bool
	for _, c := range root.Commands() {
		if c.Name() == "docs" {
			v := c.Hidden
			found = &v
		}
	}

	require.NotNil(t, found, "docs command must be registered on root")
	require.True(t, *found, "docs command must be Hidden so it doesn't clutter --help")
}

// TestDocsManCommandRunEWritesRealTree exercises the wired `docs man` RunE
// closure through the real root (--dir flag, MkdirAll, cmd.Root()
// resolution), not just the underlying doc.GenManTree call.
func TestDocsManCommandRunEWritesRealTree(t *testing.T) {
	dir := t.TempDir()
	root := NewRootCommand()

	target, _, err := root.Find([]string{"docs", "man"})
	require.NoError(t, err)
	require.NoError(t, target.Flags().Set("dir", dir))

	require.NoError(t, target.RunE(target, nil))

	require.FileExists(t, filepath.Join(dir, "spacetraders-ship-list.1"))
}

// TestDocsMarkdownCommandRunEWritesRealTree mirrors
// TestDocsManCommandRunEWritesRealTree for `docs markdown`.
func TestDocsMarkdownCommandRunEWritesRealTree(t *testing.T) {
	dir := t.TempDir()
	root := NewRootCommand()

	target, _, err := root.Find([]string{"docs", "markdown"})
	require.NoError(t, err)
	require.NoError(t, target.Flags().Set("dir", dir))

	require.NoError(t, target.RunE(target, nil))

	require.FileExists(t, filepath.Join(dir, "spacetraders_ship_list.md"))
}

// TestDocsSubcommandDefaultDirs pins the default --dir values to what the
// Makefile targets (man, cli-docs) assume, so the two can't silently drift.
func TestDocsSubcommandDefaultDirs(t *testing.T) {
	manCmd := newDocsManCommand()
	flag := manCmd.Flags().Lookup("dir")
	require.NotNil(t, flag)
	require.Equal(t, "build/man/man1", flag.DefValue)

	markdownCmd := newDocsMarkdownCommand()
	flag = markdownCmd.Flags().Lookup("dir")
	require.NotNil(t, flag)
	require.Equal(t, "docs/cli", flag.DefValue)
}

// TestDocsMarkdownCommandOmitsAutoGenTag guards against a real near-miss:
// cobra's doc generators stamp an "Autogenerated by spf13/cobra on <date>"
// footer into every file by default. docs/cli/*.md is committed for
// reviewable diffs (see Makefile), so an unsuppressed date footer would dirty
// all 120 files on every `make cli-docs` regen regardless of whether any
// command actually changed — defeating the entire point of committing them.
// `docs man`/`docs markdown` set root.DisableAutoGenTag = true before
// generating; this asserts that actually holds for the real RunE path (not
// just the bare doc.GenMarkdownTree calls in the smoke tests above, which
// intentionally don't exercise that flag).
func TestDocsMarkdownCommandOmitsAutoGenTag(t *testing.T) {
	dir := t.TempDir()
	root := NewRootCommand()

	target, _, err := root.Find([]string{"docs", "markdown"})
	require.NoError(t, err)
	require.NoError(t, target.Flags().Set("dir", dir))
	require.NoError(t, target.RunE(target, nil))

	content, err := os.ReadFile(filepath.Join(dir, "spacetraders_ship_list.md"))
	require.NoError(t, err)
	require.NotContains(t, string(content), "Auto generated by spf13/cobra",
		"generated markdown must not carry a date-stamped footer — it would dirty every committed file on every regen")
}

// TestDocsManCommandOmitsAutoGenTag mirrors
// TestDocsMarkdownCommandOmitsAutoGenTag for the man-page generator. Man
// pages (build/man/man1) are gitignored so a date footer wouldn't dirty a
// commit, but DisableAutoGenTag lives on the shared root command — this
// pins the man path to the same behavior so the two subcommands can't
// silently diverge.
func TestDocsManCommandOmitsAutoGenTag(t *testing.T) {
	dir := t.TempDir()
	root := NewRootCommand()

	target, _, err := root.Find([]string{"docs", "man"})
	require.NoError(t, err)
	require.NoError(t, target.Flags().Set("dir", dir))
	require.NoError(t, target.RunE(target, nil))

	content, err := os.ReadFile(filepath.Join(dir, "spacetraders-ship-list.1"))
	require.NoError(t, err)
	require.NotContains(t, string(content), "Auto generated by spf13/cobra",
		"generated man page must not carry a date-stamped footer")
}
