package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// NewDocsCommand generates man pages and a markdown reference from the live
// cobra command tree (`spacetraders docs man` / `spacetraders docs
// markdown`). Every command already carries Use/Short/Long/flags for
// --help, so the help tree is complete by construction; this is a thin
// wrapper around cobra's own doc generators rather than a hand-rolled
// walker, so generated docs can never drift from the binary that produced
// them. `make man` / `make cli-docs` are the intended entry points
// (gobot/Makefile).
//
// This is a separate, complementary artifact to
// scripts/gen-cli-reference.sh, which regenerates captain/CLI_REFERENCE.md
// (a single concatenated --help dump for the captain session to read in one
// shot). This command instead produces one file per command — a browsable
// reference (docs/cli/*.md) and installable man pages (build/man/man1/*.1)
// — for a different audience/consumption mode. Both may coexist.
//
// Hidden from `spacetraders --help`: it documents the tree, so surfacing it
// in the tree it documents is noise for end users.
func NewDocsCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:    "docs",
		Short:  "Generate CLI documentation (man pages, markdown) from the command tree",
		Long:   `Generate CLI documentation from the live cobra command tree. See "man" and "markdown" subcommands.`,
		Hidden: true,
	}

	cmd.AddCommand(newDocsManCommand())
	cmd.AddCommand(newDocsMarkdownCommand())

	return cmd
}

func newDocsManCommand() *cobra.Command {
	var dir string

	cmd := &cobra.Command{
		Use:   "man",
		Short: "Generate man pages (section 1) for every command into --dir",
		Long: `Generate a man page (section 1) for every command and subcommand in the
tree, one file per command (e.g. spacetraders-ship-list.1), into --dir.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return fmt.Errorf("create man output dir %s: %w", dir, err)
			}
			header := &doc.GenManHeader{
				Title:   "SPACETRADERS",
				Section: "1",
				// A non-empty Source sidesteps a cobra quirk: GenMan fills
				// header.Source (the .TH line's 4th field) via a header-first,
				// body-second pass, so DisableAutoGenTag below — set on the
				// child command, one level too late relative to that pass —
				// only suppresses the "# HISTORY" footer, not this line. An
				// explicit Source is copied verbatim per command regardless of
				// that ordering, so every page gets a real value here instead
				// of "Auto generated by spf13/cobra".
				Source: "spacetraders CLI",
			}
			// cmd.Root(), not NewRootCommand(): walk the tree actually being
			// executed rather than constructing a second, parallel instance.
			root := cmd.Root()
			// Suppresses the "# HISTORY\n<date> Auto generated by spf13/cobra"
			// footer tree-wide (propagates to descendants via cobra's own
			// VisitParents check in doc.GenManTree). build/man is gitignored,
			// so this is cosmetic rather than a diff-stability concern here —
			// unlike the markdown tree below, which is committed.
			root.DisableAutoGenTag = true
			if err := doc.GenManTree(root, header, dir); err != nil {
				return fmt.Errorf("generate man pages into %s: %w", dir, err)
			}
			fmt.Printf("wrote man pages to %s\n", dir)
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", "build/man/man1", "Output directory for generated man pages")

	return cmd
}

func newDocsMarkdownCommand() *cobra.Command {
	var dir string

	cmd := &cobra.Command{
		Use:   "markdown",
		Short: "Generate a markdown reference for every command into --dir",
		Long: `Generate a markdown reference page for every command and subcommand in
the tree, one file per command (e.g. spacetraders_ship_list.md), into --dir.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return fmt.Errorf("create markdown output dir %s: %w", dir, err)
			}
			root := cmd.Root()
			// Suppress the "Auto generated by spf13/cobra on <date>" footer:
			// docs/cli is committed for reviewable diffs, so a per-run date
			// stamp would dirty all 120 files on every regen even when no
			// command actually changed.
			root.DisableAutoGenTag = true
			if err := doc.GenMarkdownTree(root, dir); err != nil {
				return fmt.Errorf("generate markdown reference into %s: %w", dir, err)
			}
			fmt.Printf("wrote markdown reference to %s\n", dir)
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", "docs/cli", "Output directory for generated markdown reference")

	return cmd
}
