package trading

import (
	"math"
	"testing"
)

// relocation_travel_model_test.go — the swappable travel-time seam behind the opportunity
// relocator's NPV (sp-zvywu Part 2).

// crossingSecondsFixture is the sp-smbgd affine model's OWN PUBLISHED crossing charge by gate-hop
// depth, quoted from the commit that shipped it ("1 hop 1200 -> 1400 ... 2 hop 2400 -> 2050, 3 hop
// 3600 -> 2700, 4 hop 4800 -> 3350, 5 hop 6000 -> 4000"). Using the published charges as the oracle
// — rather than recomputing base + perHop*h in the test — keeps the assertion independent of the
// implementation: if someone changes the arithmetic, these numbers do not move with it.
var crossingSecondsFixture = map[int]float64{1: 1400, 2: 2050, 3: 2700, 4: 3350, 5: 4000}

// measuredMediansFixture is the MEASURED table sp-smbgd fitted on: median crossing seconds by
// gate-hop depth over 24h, n=567. This is the shape a cap-2 re-measurement produces, so it is also
// the fixture for the refit path.
var measuredMediansFixture = map[int]float64{1: 1376, 2: 2105, 3: 2732, 4: 3571, 5: 3786, 6: 4161}

func TestAffineHopModelShould_PriceACrossingAtItsPublishedAffineCharge(t *testing.T) {
	model := DefaultAffineHopModel()

	for hops, wantSeconds := range crossingSecondsFixture {
		gotHours := model.CrossingHours(hops)
		wantHours := wantSeconds / 3600
		if math.Abs(gotHours-wantHours) > 1e-9 {
			t.Fatalf("crossing of %d gate hops priced at %.6f h, want %.6f h (%.0f s, the sp-smbgd published charge)",
				hops, gotHours, wantHours, wantSeconds)
		}
	}
}

func TestAffineHopModelShould_ChargeNothingForASameSystemCrossing(t *testing.T) {
	model := DefaultAffineHopModel()

	for _, hops := range []int{0, -1} {
		if got := model.CrossingHours(hops); got != 0 {
			t.Fatalf("a %d-hop (same-system) crossing priced at %.6f h, want 0 — a hull already in the region pays no travel", hops, got)
		}
	}
}

// A zero-value or badly-conditioned model must never price a crossing at zero: a free crossing
// makes every distant region look costless and would let a bad refit license unlimited relocation.
func TestAffineHopModelShould_NeverPriceACrossingAsFree_GivenAnUnsetOrDegenerateModel(t *testing.T) {
	floorHours := 2 * CrossingTermMinSeconds / 3600 // one clamped base + one clamped per-hop term

	for name, model := range map[string]AffineHopModel{
		"unset (zero value)":   {},
		"negative base":        {BaseSeconds: -100, PerHopSeconds: -100},
		"below the term floor": {BaseSeconds: 1, PerHopSeconds: 1},
	} {
		got := model.CrossingHours(1)
		if got < floorHours {
			t.Fatalf("%s priced a 1-hop crossing at %.6f h, below the clamped floor %.6f h — a free crossing makes every distant region look costless", name, got, floorHours)
		}
	}
}

// A refit must not be able to price a crossing arbitrarily high either, or one bad coefficient
// silently freezes all relocation.
func TestAffineHopModelShould_ClampAnAbsurdlyHighRefitToTheTermCeiling(t *testing.T) {
	absurd := AffineHopModel{BaseSeconds: 1e9, PerHopSeconds: 1e9}

	got := absurd.CrossingHours(2)
	wantCeiling := (CrossingTermMaxSeconds + 2*CrossingTermMaxSeconds) / 3600
	if math.Abs(got-wantCeiling) > 1e-9 {
		t.Fatalf("an absurd refit priced a 2-hop crossing at %.6f h, want the clamped ceiling %.6f h", got, wantCeiling)
	}
}

// THE REFIT PATH, part 1: the fitter must be an ACTUAL least-squares fit. Fed a table generated by
// an exactly affine law, it must return that law's own coefficients — an oracle traced to the
// definition of the model rather than to the arithmetic under test.
func TestFitAffineHopModelShould_RecoverTheCoefficientsOfAnExactlyAffineTable(t *testing.T) {
	const wantBase, wantPerHop = 800.0, 700.0
	exact := map[int]float64{}
	for hops := 1; hops <= 6; hops++ {
		exact[hops] = wantBase + wantPerHop*float64(hops)
	}

	fitted, ok := FitAffineHopModel(exact)
	if !ok {
		t.Fatal("fitting an exactly affine table reported not-ok")
	}
	if math.Abs(fitted.BaseSeconds-wantBase) > 1e-6 {
		t.Fatalf("refit base %.6f s, want %.1f s — the fitter does not recover an exactly affine law", fitted.BaseSeconds, wantBase)
	}
	if math.Abs(fitted.PerHopSeconds-wantPerHop) > 1e-6 {
		t.Fatalf("refit per-hop %.6f s, want %.1f s — the fitter does not recover an exactly affine law", fitted.PerHopSeconds, wantPerHop)
	}
}

// THE REFIT PATH, part 2: fitted on real measured medians, the candidate model must TRACK those
// medians inside the same 15% bar the drift check gates on. This is the property that makes the
// refit path usable — a cap-2 re-measurement plus this one call yields a model good enough to price
// travel with, with no NPV code touched.
//
// It deliberately does NOT assert the published 749 + 661 intercept/slope split: that fit was
// WEIGHTED by per-depth sample count, this one is not, and the two split a near-identical total
// differently (974 + 566 here). Median tracking is the property both fits actually share, and it is
// what the NPV consumes.
func TestFitAffineHopModelShould_TrackTheMeasuredMediansWithinTheDriftBar(t *testing.T) {
	fitted, ok := FitAffineHopModel(measuredMediansFixture)
	if !ok {
		t.Fatal("fitting the sp-smbgd measured medians reported not-ok; the refit path must work on the very table it was fitted from")
	}

	if fitted.MedianDriftExceeds(measuredMediansFixture, 0.15) {
		t.Fatalf("a model fitted ON the measured medians drifts >15%% off them (base %.1f, per-hop %.1f) — the refit path does not produce an adoptable model", fitted.BaseSeconds, fitted.PerHopSeconds)
	}
}

// A refit that cannot determine a line must FAIL rather than return invented coefficients — the
// caller then keeps the model it has instead of relocating off a fabricated travel time.
func TestFitAffineHopModelShould_FailClosed_GivenATableThatCannotDetermineALine(t *testing.T) {
	for name, table := range map[string]map[int]float64{
		"empty":                              {},
		"a single depth":                     {2: 2050},
		"a zero median (a hole in the data)": {1: 1400, 2: 0},
		"a negative median":                  {1: 1400, 2: -5},
		"a non-positive depth":               {0: 750, 2: 2050},
	} {
		if _, ok := FitAffineHopModel(table); ok {
			t.Fatalf("fitting %s reported ok; an undeterminable fit must fail closed so the caller keeps its existing model", name)
		}
	}
}

// The standing "is a refit due?" check: sp-zvywu spec v2's 15% bar.
func TestAffineHopModelShould_FlagDriftOnlyWhenAMeasuredDepthMovesPastTheTolerance(t *testing.T) {
	model := DefaultAffineHopModel()

	if model.MedianDriftExceeds(measuredMediansFixture, 0.15) {
		t.Fatal("the fitted model reports >15% drift against the very medians it was fitted on — the re-verification check would demand a refit on arrival")
	}

	// Shift ONE deep median far enough to change the model's SHAPE. Depth 5 predicted at 4000 s;
	// a measured 8000 s is 100% off, well past the bar.
	shifted := map[int]float64{1: 1376, 2: 2105, 3: 2732, 4: 3571, 5: 8000, 6: 4161}
	if !model.MedianDriftExceeds(shifted, 0.15) {
		t.Fatal("a deep median measured at double the model's prediction did not trip the 15% drift check — a cap-2 shape change would go unnoticed")
	}
}

// A single depth drifting must be enough. An averaged check would hide a shape change that only
// shows at depth, which is exactly the cap-revert failure mode spec v2 warns about.
func TestAffineHopModelShould_FlagDriftFromASingleDeepDepth_NotOnlyFromTheAverage(t *testing.T) {
	model := DefaultAffineHopModel()

	// Every shallow depth fits perfectly; only depth 6 moves. The mean absolute drift across the
	// table stays under the bar, so only a per-depth check can catch this.
	onlyDeepDrift := map[int]float64{1: 1400, 2: 2050, 3: 2700, 4: 3350, 5: 4000, 6: 7000}
	if !model.MedianDriftExceeds(onlyDeepDrift, 0.15) {
		t.Fatal("drift confined to depth 6 did not trip the check; a shape change at depth is the cap-revert failure mode and must not be averaged away")
	}
}

// THE RELATIVE REFIT PATH, for the measured cap-2 shift. The analyst's −35% per crossing is a
// per-crossing figure whose unit is not the model's (a crossing may span several gate hops), so the
// LEVEL is what it licenses changing, not the base:per-hop split. ScaledBy must therefore move every
// crossing by exactly the measured fraction and leave the fitted ratio alone.
func TestAffineHopModelShould_ApplyARelativeRefitToEveryCrossingWhileHoldingTheFittedRatio(t *testing.T) {
	fitted := DefaultAffineHopModel()
	const capTwoFactor = 0.65 // the measured −35% shift

	refitted := fitted.ScaledBy(capTwoFactor)

	for hops := 1; hops <= 6; hops++ {
		want := fitted.CrossingHours(hops) * capTwoFactor
		if math.Abs(refitted.CrossingHours(hops)-want) > 1e-9 {
			t.Fatalf("a 0.65 relative refit priced a %d-hop crossing at %.6f h, want %.6f h (35%% cheaper than the armed model)",
				hops, refitted.CrossingHours(hops), want)
		}
	}
	// The fitted base:per-hop ratio is what a per-crossing measurement cannot re-split, so it must
	// survive the scaling untouched.
	wantRatio := fitted.BaseSeconds / fitted.PerHopSeconds
	if gotRatio := refitted.BaseSeconds / refitted.PerHopSeconds; math.Abs(gotRatio-wantRatio) > 1e-9 {
		t.Fatalf("a relative refit changed the base:per-hop ratio to %.6f, want the fitted %.6f — a per-crossing shift cannot re-split the terms", gotRatio, wantRatio)
	}
}

// A refit must be a coefficient change, NEVER a code change: the same NPV call must price the same
// move differently through a rescaled model, with nothing else touched.
func TestAffineHopModelShould_ChangeAValuationThroughCoefficientsAlone(t *testing.T) {
	base := RelocationInputs{
		CurrentRate: 100_000, ProjectedRate: 400_000,
		RemainingEraHours: 48, EraHorizonKnown: true, HorizonHours: 24,
		RiskMargin: 100_000, UpliftBar: 1.5, NPVThreshold: 0,
	}
	armed := DefaultAffineHopModel()
	cheaper := armed.ScaledBy(0.65)

	dear := base
	dear.TravelHours = armed.CrossingHours(2)
	cheap := base
	cheap.TravelHours = cheaper.CrossingHours(2)

	dearValuation, cheapValuation := ValueRelocation(dear), ValueRelocation(cheap)
	if !dearValuation.Licensed() || !cheapValuation.Licensed() {
		t.Fatalf("both valuations should be licensed; got %q and %q", dearValuation.Verdict, cheapValuation.Verdict)
	}
	// Cheaper travel means a shorter unpaid flight and a longer productive window, so the SAME move is
	// worth strictly more — the direction the analyst predicted, produced by coefficients alone.
	if cheapValuation.NPV <= dearValuation.NPV {
		t.Fatalf("a 35%%-cheaper travel model valued the same move at %.0f, not more than the armed model's %.0f", cheapValuation.NPV, dearValuation.NPV)
	}
}

// A degenerate scaling factor must not make crossings nearly free.
func TestAffineHopModelShould_RefuseANonPositiveRelativeRefit(t *testing.T) {
	fitted := DefaultAffineHopModel()

	for _, factor := range []float64{0, -1} {
		if got := fitted.ScaledBy(factor); got != fitted {
			t.Fatalf("scaling by %v returned %+v, want the model unchanged — a zero-scaled model prices every distant region as nearly free", factor, got)
		}
	}
}

// No measurement is not evidence of drift — the caller must keep the model it has.
func TestAffineHopModelShould_ReportNoDrift_GivenNoMeasurements(t *testing.T) {
	if DefaultAffineHopModel().MedianDriftExceeds(map[int]float64{}, 0.15) {
		t.Fatal("an empty median table reported drift; absence of measurement must not force a refit")
	}
}

// ---------------------------------------------------------------------------------------
// ArrivalBoundHopModel — the GUARD's travel model.
// ---------------------------------------------------------------------------------------

// measuredP90Fixture is the MEASURED p90 crossing seconds by gate-hop depth (2026-07-30,
// tour_leg_telemetry, n=868 over depths 1-5 — the whole range gategraph.MaxJumpPath admits),
// quoted from the measurement the factor was chosen on rather than recomputed here.
var measuredP90Fixture = map[int]float64{1: 1630, 2: 2720, 3: 3441, 4: 3899, 5: 4415}

// The bound must track the measured p90 arrival, not merely sit somewhere above the median.
// MedianDriftExceeds is the codebase's own "does this model track this table" check, so the
// assertion is the same one a refit would run.
func TestArrivalBoundHopModelShould_TrackTheMeasuredP90ArrivalTable(t *testing.T) {
	if ArrivalBoundHopModel().MedianDriftExceeds(measuredP90Fixture, 0.10) {
		t.Fatalf("the arrival bound drifts more than 10%% off the measured p90 at some depth; "+
			"model %+v against %v", ArrivalBoundHopModel(), measuredP90Fixture)
	}
}

// ...and the fixture DISCRIMINATES: the median model — what the guard would use if the
// headroom factor were dropped — fails that same bar. Without this, the test above passes on
// any model loose enough to be useless.
func TestArrivalBoundHopModelShould_RejectTheMedianModelAgainstTheSameP90Bar(t *testing.T) {
	if !DefaultAffineHopModel().MedianDriftExceeds(measuredP90Fixture, 0.10) {
		t.Fatalf("the MEDIAN model must NOT track the p90 table within 10%% — if it does, the p90 " +
			"fixture cannot tell an arrival bound from an expected-value price and proves nothing")
	}
}

// A guard is late-averse where an objective is not: the bound must exceed the published median
// charge at EVERY depth a strict flight bound can produce, or the freshness cap it feeds is
// being held at a coin-flip arrival.
func TestArrivalBoundHopModelShould_ExceedTheMedianChargeAtEveryReachableDepth(t *testing.T) {
	bound, median := ArrivalBoundHopModel(), DefaultAffineHopModel()

	for hops := 1; hops <= 5; hops++ {
		if got, want := bound.CrossingHours(hops), median.CrossingHours(hops); got <= want {
			t.Fatalf("a %d-hop crossing bounds arrival at %.4f h but is PRICED at %.4f h — an arrival "+
				"bound at or below the median is wrong half the time", hops, got, want)
		}
	}
}

// The bound is the median model SCALED, not a second set of coefficients: a refit of the armed
// constants must carry the guard with it rather than leave it stale beside them.
func TestArrivalBoundHopModelShould_FollowARefitOfTheMedianCoefficients(t *testing.T) {
	bound := ArrivalBoundHopModel()
	wantBase := DefaultCrossingBaseSeconds * ArrivalP90HeadroomFactor
	wantPerHop := DefaultCrossingPerHopSeconds * ArrivalP90HeadroomFactor

	if math.Abs(bound.BaseSeconds-wantBase) > 1e-9 || math.Abs(bound.PerHopSeconds-wantPerHop) > 1e-9 {
		t.Fatalf("arrival bound is %+v, want the armed coefficients scaled by %.2f (%.1f, %.1f) — a "+
			"hand-written second pair would go stale the first time the median model is refitted",
			bound, ArrivalP90HeadroomFactor, wantBase, wantPerHop)
	}
}

// ── THE MEASURED-LEVEL ADOPTION PATH (sp-80mha) ──────────────────────────────────────────────────
//
// The sp-3x143 estimator hands back ONE number — the measured MARGINAL per-hop toll — and the
// contract above says a partial measurement moves the LEVEL via ScaledBy and leaves the SHAPE
// alone, adopted only when MedianDriftExceeds says a refit is due. These tests pin both
// directions of that adoption with the exact levels the two live readings imply.

// The DOWN direction: the fleet's own recorded cap-2 evidence points BELOW the armed 650 (a
// per-hop toll of 423 is the −35% level). The incumbent drifts (650−423)/423 ≈ 54% off the
// measured level — far past the spec bar — so the model must re-level down, holding the fitted
// base:per-hop ratio, and price every crossing at exactly the implied cheaper level.
func TestAffineHopModelShould_ReLevelDownToAMeasuredPerHopTollPastTheDriftBar(t *testing.T) {
	adopted, ok := DefaultAffineHopModel().AdoptMeasuredPerHopLevel(423)

	if !ok {
		t.Fatalf("a 54%% drift must adopt the measured level, got the incumbent %+v", adopted)
	}
	wantHours := 1400.0 * 423.0 / 650.0 / 3600.0 // the incumbent 1-hop charge at the implied level
	if got := adopted.CrossingHours(1); math.Abs(got-wantHours) > 1e-9 {
		t.Fatalf("re-levelled 1-hop crossing priced at %.9f h, want exactly %.9f h (1400s x 423/650)", got, wantHours)
	}
	if got := adopted.CrossingHours(1); got >= DefaultAffineHopModel().CrossingHours(1) {
		t.Fatalf("a measured toll BELOW the armed term must price crossings CHEAPER, got %.6f h >= %.6f h",
			got, DefaultAffineHopModel().CrossingHours(1))
	}
	wantRatio := DefaultCrossingBaseSeconds / DefaultCrossingPerHopSeconds
	if gotRatio := adopted.BaseSeconds / adopted.PerHopSeconds; math.Abs(gotRatio-wantRatio) > 1e-9 {
		t.Fatalf("adoption must move the LEVEL and hold the SHAPE: base:per-hop ratio %.9f, want %.9f", gotRatio, wantRatio)
	}
}

// The UP direction: the live wall-clock median the estimator serves (1028s) sits ABOVE the armed
// 650, so the same adoption must price crossings dearer by exactly the implied factor.
func TestAffineHopModelShould_ReLevelUpToTheMeasuredMedianPerHopToll(t *testing.T) {
	adopted, ok := DefaultAffineHopModel().AdoptMeasuredPerHopLevel(1028)

	if !ok {
		t.Fatalf("a ~58%% level shift must adopt the measured toll, got the incumbent %+v", adopted)
	}
	wantHours := 1400.0 * 1028.0 / 650.0 / 3600.0
	if got := adopted.CrossingHours(1); math.Abs(got-wantHours) > 1e-9 {
		t.Fatalf("re-levelled 1-hop crossing priced at %.9f h, want exactly %.9f h (1400s x 1028/650)", got, wantHours)
	}
	if got := adopted.CrossingHours(1); got <= DefaultAffineHopModel().CrossingHours(1) {
		t.Fatalf("a measured toll ABOVE the armed term must price crossings DEARER, got %.6f h <= %.6f h",
			got, DefaultAffineHopModel().CrossingHours(1))
	}
}

// Inside the spec bar the incumbent STANDS: drift within tolerance is noise, and re-levelling on
// it would churn the NPV on every estimator wobble the bar exists to absorb. Just past the bar,
// the level moves. Both edges, both sides of 650.
func TestAffineHopModelShould_AdoptOnlyWhenTheDriftClearsTheSpecBar(t *testing.T) {
	incumbent := DefaultAffineHopModel()
	for measured, wantAdopt := range map[float64]bool{
		570: false, // (650-570)/570 ≈ 14.0% — inside the bar
		560: true,  // (650-560)/560 ≈ 16.1% — past it
		764: false, // (764-650)/764 ≈ 14.9% — inside the bar
		765: true,  // (765-650)/765 ≈ 15.0%+ — past it
	} {
		adopted, ok := incumbent.AdoptMeasuredPerHopLevel(measured)
		if ok != wantAdopt {
			t.Fatalf("measured %v: adopted=%v, want %v (the spec's 15%% drift bar)", measured, ok, wantAdopt)
		}
		if !wantAdopt && adopted != incumbent {
			t.Fatalf("a within-bar measurement must return the incumbent unchanged, got %+v", adopted)
		}
	}
}

// A non-positive toll is the estimator's fail-open silence (too few samples, an unwired reader),
// not a measurement: the incumbent must survive untouched so the cold case prices exactly as the
// fitted constants always have.
func TestAffineHopModelShould_KeepTheIncumbent_GivenNoMeasuredToll(t *testing.T) {
	incumbent := DefaultAffineHopModel()
	for _, silent := range []float64{0, -100} {
		adopted, ok := incumbent.AdoptMeasuredPerHopLevel(silent)
		if ok || adopted != incumbent {
			t.Fatalf("toll %v is silence, not evidence: want the incumbent unchanged, got adopted=%v %+v", silent, ok, adopted)
		}
	}
}

// A zero-value model's EFFECTIVE terms are the fitted defaults (the clamp's unset fallback), so
// adoption from it must land on the same level as adoption from the default model — never on a
// division by an unset zero term.
func TestAffineHopModelShould_ReLevelAnUnsetModelFromItsEffectiveFittedTerms(t *testing.T) {
	fromUnset, okUnset := AffineHopModel{}.AdoptMeasuredPerHopLevel(1028)
	fromDefault, okDefault := DefaultAffineHopModel().AdoptMeasuredPerHopLevel(1028)

	if !okUnset || !okDefault {
		t.Fatalf("both models must adopt the 1028 level, got unset=%v default=%v", okUnset, okDefault)
	}
	if math.Abs(fromUnset.CrossingHours(3)-fromDefault.CrossingHours(3)) > 1e-9 {
		t.Fatalf("an unset model must re-level from its effective fitted terms: %.9f h vs %.9f h",
			fromUnset.CrossingHours(3), fromDefault.CrossingHours(3))
	}
}
