package trading

import (
	"math"
	"testing"
)

// relocation_travel_model_test.go — the swappable travel-time seam behind the opportunity
// relocator's NPV (sp-zvywu Part 2).

// crossingSecondsFixture is the sp-smbgd affine model's OWN PUBLISHED crossing charge by gate-hop
// depth, quoted from the commit that shipped it ("1 hop 1200 -> 1400 ... 2 hop 2400 -> 2050, 3 hop
// 3600 -> 2700, 4 hop 4800 -> 3350, 5 hop 6000 -> 4000"). Using the published charges as the oracle
// — rather than recomputing base + perHop*h in the test — keeps the assertion independent of the
// implementation: if someone changes the arithmetic, these numbers do not move with it.
var crossingSecondsFixture = map[int]float64{1: 1400, 2: 2050, 3: 2700, 4: 3350, 5: 4000}

// measuredMediansFixture is the MEASURED table sp-smbgd fitted on: median crossing seconds by
// gate-hop depth over 24h, n=567. This is the shape a cap-2 re-measurement produces, so it is also
// the fixture for the refit path.
var measuredMediansFixture = map[int]float64{1: 1376, 2: 2105, 3: 2732, 4: 3571, 5: 3786, 6: 4161}

func TestAffineHopModelShould_PriceACrossingAtItsPublishedAffineCharge(t *testing.T) {
	model := DefaultAffineHopModel()

	for hops, wantSeconds := range crossingSecondsFixture {
		gotHours := model.CrossingHours(hops)
		wantHours := wantSeconds / 3600
		if math.Abs(gotHours-wantHours) > 1e-9 {
			t.Fatalf("crossing of %d gate hops priced at %.6f h, want %.6f h (%.0f s, the sp-smbgd published charge)",
				hops, gotHours, wantHours, wantSeconds)
		}
	}
}

func TestAffineHopModelShould_ChargeNothingForASameSystemCrossing(t *testing.T) {
	model := DefaultAffineHopModel()

	for _, hops := range []int{0, -1} {
		if got := model.CrossingHours(hops); got != 0 {
			t.Fatalf("a %d-hop (same-system) crossing priced at %.6f h, want 0 — a hull already in the region pays no travel", hops, got)
		}
	}
}

// A zero-value or badly-conditioned model must never price a crossing at zero: a free crossing
// makes every distant region look costless and would let a bad refit license unlimited relocation.
func TestAffineHopModelShould_NeverPriceACrossingAsFree_GivenAnUnsetOrDegenerateModel(t *testing.T) {
	floorHours := 2 * CrossingTermMinSeconds / 3600 // one clamped base + one clamped per-hop term

	for name, model := range map[string]AffineHopModel{
		"unset (zero value)":   {},
		"negative base":        {BaseSeconds: -100, PerHopSeconds: -100},
		"below the term floor": {BaseSeconds: 1, PerHopSeconds: 1},
	} {
		got := model.CrossingHours(1)
		if got < floorHours {
			t.Fatalf("%s priced a 1-hop crossing at %.6f h, below the clamped floor %.6f h — a free crossing makes every distant region look costless", name, got, floorHours)
		}
	}
}

// A refit must not be able to price a crossing arbitrarily high either, or one bad coefficient
// silently freezes all relocation.
func TestAffineHopModelShould_ClampAnAbsurdlyHighRefitToTheTermCeiling(t *testing.T) {
	absurd := AffineHopModel{BaseSeconds: 1e9, PerHopSeconds: 1e9}

	got := absurd.CrossingHours(2)
	wantCeiling := (CrossingTermMaxSeconds + 2*CrossingTermMaxSeconds) / 3600
	if math.Abs(got-wantCeiling) > 1e-9 {
		t.Fatalf("an absurd refit priced a 2-hop crossing at %.6f h, want the clamped ceiling %.6f h", got, wantCeiling)
	}
}

// THE REFIT PATH, part 1: the fitter must be an ACTUAL least-squares fit. Fed a table generated by
// an exactly affine law, it must return that law's own coefficients — an oracle traced to the
// definition of the model rather than to the arithmetic under test.
func TestFitAffineHopModelShould_RecoverTheCoefficientsOfAnExactlyAffineTable(t *testing.T) {
	const wantBase, wantPerHop = 800.0, 700.0
	exact := map[int]float64{}
	for hops := 1; hops <= 6; hops++ {
		exact[hops] = wantBase + wantPerHop*float64(hops)
	}

	fitted, ok := FitAffineHopModel(exact)
	if !ok {
		t.Fatal("fitting an exactly affine table reported not-ok")
	}
	if math.Abs(fitted.BaseSeconds-wantBase) > 1e-6 {
		t.Fatalf("refit base %.6f s, want %.1f s — the fitter does not recover an exactly affine law", fitted.BaseSeconds, wantBase)
	}
	if math.Abs(fitted.PerHopSeconds-wantPerHop) > 1e-6 {
		t.Fatalf("refit per-hop %.6f s, want %.1f s — the fitter does not recover an exactly affine law", fitted.PerHopSeconds, wantPerHop)
	}
}

// THE REFIT PATH, part 2: fitted on real measured medians, the candidate model must TRACK those
// medians inside the same 15% bar the drift check gates on. This is the property that makes the
// refit path usable — a cap-2 re-measurement plus this one call yields a model good enough to price
// travel with, with no NPV code touched.
//
// It deliberately does NOT assert the published 749 + 661 intercept/slope split: that fit was
// WEIGHTED by per-depth sample count, this one is not, and the two split a near-identical total
// differently (974 + 566 here). Median tracking is the property both fits actually share, and it is
// what the NPV consumes.
func TestFitAffineHopModelShould_TrackTheMeasuredMediansWithinTheDriftBar(t *testing.T) {
	fitted, ok := FitAffineHopModel(measuredMediansFixture)
	if !ok {
		t.Fatal("fitting the sp-smbgd measured medians reported not-ok; the refit path must work on the very table it was fitted from")
	}

	if fitted.MedianDriftExceeds(measuredMediansFixture, 0.15) {
		t.Fatalf("a model fitted ON the measured medians drifts >15%% off them (base %.1f, per-hop %.1f) — the refit path does not produce an adoptable model", fitted.BaseSeconds, fitted.PerHopSeconds)
	}
}

// A refit that cannot determine a line must FAIL rather than return invented coefficients — the
// caller then keeps the model it has instead of relocating off a fabricated travel time.
func TestFitAffineHopModelShould_FailClosed_GivenATableThatCannotDetermineALine(t *testing.T) {
	for name, table := range map[string]map[int]float64{
		"empty":                              {},
		"a single depth":                     {2: 2050},
		"a zero median (a hole in the data)": {1: 1400, 2: 0},
		"a negative median":                  {1: 1400, 2: -5},
		"a non-positive depth":               {0: 750, 2: 2050},
	} {
		if _, ok := FitAffineHopModel(table); ok {
			t.Fatalf("fitting %s reported ok; an undeterminable fit must fail closed so the caller keeps its existing model", name)
		}
	}
}

// The standing "is a refit due?" check: sp-zvywu spec v2's 15% bar.
func TestAffineHopModelShould_FlagDriftOnlyWhenAMeasuredDepthMovesPastTheTolerance(t *testing.T) {
	model := DefaultAffineHopModel()

	if model.MedianDriftExceeds(measuredMediansFixture, 0.15) {
		t.Fatal("the fitted model reports >15% drift against the very medians it was fitted on — the re-verification check would demand a refit on arrival")
	}

	// Shift ONE deep median far enough to change the model's SHAPE. Depth 5 predicted at 4000 s;
	// a measured 8000 s is 100% off, well past the bar.
	shifted := map[int]float64{1: 1376, 2: 2105, 3: 2732, 4: 3571, 5: 8000, 6: 4161}
	if !model.MedianDriftExceeds(shifted, 0.15) {
		t.Fatal("a deep median measured at double the model's prediction did not trip the 15% drift check — a cap-2 shape change would go unnoticed")
	}
}

// A single depth drifting must be enough. An averaged check would hide a shape change that only
// shows at depth, which is exactly the cap-revert failure mode spec v2 warns about.
func TestAffineHopModelShould_FlagDriftFromASingleDeepDepth_NotOnlyFromTheAverage(t *testing.T) {
	model := DefaultAffineHopModel()

	// Every shallow depth fits perfectly; only depth 6 moves. The mean absolute drift across the
	// table stays under the bar, so only a per-depth check can catch this.
	onlyDeepDrift := map[int]float64{1: 1400, 2: 2050, 3: 2700, 4: 3350, 5: 4000, 6: 7000}
	if !model.MedianDriftExceeds(onlyDeepDrift, 0.15) {
		t.Fatal("drift confined to depth 6 did not trip the check; a shape change at depth is the cap-revert failure mode and must not be averaged away")
	}
}

// THE RELATIVE REFIT PATH, for the measured cap-2 shift. The analyst's −35% per crossing is a
// per-crossing figure whose unit is not the model's (a crossing may span several gate hops), so the
// LEVEL is what it licenses changing, not the base:per-hop split. ScaledBy must therefore move every
// crossing by exactly the measured fraction and leave the fitted ratio alone.
func TestAffineHopModelShould_ApplyARelativeRefitToEveryCrossingWhileHoldingTheFittedRatio(t *testing.T) {
	fitted := DefaultAffineHopModel()
	const capTwoFactor = 0.65 // the measured −35% shift

	refitted := fitted.ScaledBy(capTwoFactor)

	for hops := 1; hops <= 6; hops++ {
		want := fitted.CrossingHours(hops) * capTwoFactor
		if math.Abs(refitted.CrossingHours(hops)-want) > 1e-9 {
			t.Fatalf("a 0.65 relative refit priced a %d-hop crossing at %.6f h, want %.6f h (35%% cheaper than the armed model)",
				hops, refitted.CrossingHours(hops), want)
		}
	}
	// The fitted base:per-hop ratio is what a per-crossing measurement cannot re-split, so it must
	// survive the scaling untouched.
	wantRatio := fitted.BaseSeconds / fitted.PerHopSeconds
	if gotRatio := refitted.BaseSeconds / refitted.PerHopSeconds; math.Abs(gotRatio-wantRatio) > 1e-9 {
		t.Fatalf("a relative refit changed the base:per-hop ratio to %.6f, want the fitted %.6f — a per-crossing shift cannot re-split the terms", gotRatio, wantRatio)
	}
}

// A refit must be a coefficient change, NEVER a code change: the same NPV call must price the same
// move differently through a rescaled model, with nothing else touched.
func TestAffineHopModelShould_ChangeAValuationThroughCoefficientsAlone(t *testing.T) {
	base := RelocationInputs{
		CurrentRate: 100_000, ProjectedRate: 400_000,
		RemainingEraHours: 48, EraHorizonKnown: true, HorizonHours: 24,
		RiskMargin: 100_000, UpliftBar: 1.5, NPVThreshold: 0,
	}
	armed := DefaultAffineHopModel()
	cheaper := armed.ScaledBy(0.65)

	dear := base
	dear.TravelHours = armed.CrossingHours(2)
	cheap := base
	cheap.TravelHours = cheaper.CrossingHours(2)

	dearValuation, cheapValuation := ValueRelocation(dear), ValueRelocation(cheap)
	if !dearValuation.Licensed() || !cheapValuation.Licensed() {
		t.Fatalf("both valuations should be licensed; got %q and %q", dearValuation.Verdict, cheapValuation.Verdict)
	}
	// Cheaper travel means a shorter unpaid flight and a longer productive window, so the SAME move is
	// worth strictly more — the direction the analyst predicted, produced by coefficients alone.
	if cheapValuation.NPV <= dearValuation.NPV {
		t.Fatalf("a 35%%-cheaper travel model valued the same move at %.0f, not more than the armed model's %.0f", cheapValuation.NPV, dearValuation.NPV)
	}
}

// A degenerate scaling factor must not make crossings nearly free.
func TestAffineHopModelShould_RefuseANonPositiveRelativeRefit(t *testing.T) {
	fitted := DefaultAffineHopModel()

	for _, factor := range []float64{0, -1} {
		if got := fitted.ScaledBy(factor); got != fitted {
			t.Fatalf("scaling by %v returned %+v, want the model unchanged — a zero-scaled model prices every distant region as nearly free", factor, got)
		}
	}
}

// No measurement is not evidence of drift — the caller must keep the model it has.
func TestAffineHopModelShould_ReportNoDrift_GivenNoMeasurements(t *testing.T) {
	if DefaultAffineHopModel().MedianDriftExceeds(map[int]float64{}, 0.15) {
		t.Fatal("an empty median table reported drift; absence of measurement must not force a refit")
	}
}
